// Common foods database (per 100g).
//
// Historical note: earlier edits appended new rows without checking existing
// ones, which produced a handful of near-duplicates (e.g. "Шоколад тёмный 70%"
// and "Шоколад горький (70%)"). The FOOD_DB export below is deduped at module
// load: entries with the same normalized name (lowercase, trimmed, punctuation
// stripped) and identical macros collapse to one.
const RAW_FOOD_DB = [
  // Мясо и птица
  { name: 'Куриная грудка', calories: 165, protein: 31, fats: 3.6, carbs: 0 },
  { name: 'Куриное бедро', calories: 215, protein: 26, fats: 12, carbs: 0 },
  { name: 'Индейка (грудка)', calories: 157, protein: 29, fats: 3.2, carbs: 0 },
  { name: 'Говядина (фарш)', calories: 250, protein: 26, fats: 17, carbs: 0 },
  { name: 'Говядина (вырезка)', calories: 187, protein: 29, fats: 7, carbs: 0 },
  { name: 'Свинина (корейка)', calories: 270, protein: 23, fats: 19, carbs: 0 },
  { name: 'Свинина (вырезка)', calories: 143, protein: 22, fats: 6, carbs: 0 },
  { name: 'Докторская колбаса', calories: 256, protein: 13, fats: 22, carbs: 2 },
  { name: 'Куриная варёная колбаса', calories: 170, protein: 16, fats: 10, carbs: 5 },
  // Рыба и морепродукты
  { name: 'Лосось', calories: 208, protein: 20, fats: 13, carbs: 0 },
  { name: 'Горбуша', calories: 142, protein: 21, fats: 7, carbs: 0 },
  { name: 'Скумбрия', calories: 191, protein: 18, fats: 13, carbs: 0 },
  { name: 'Треска', calories: 75, protein: 17, fats: 0.6, carbs: 0 },
  { name: 'Минтай', calories: 72, protein: 16, fats: 0.9, carbs: 0 },
  { name: 'Тунец консервированный', calories: 116, protein: 25, fats: 1, carbs: 0 },
  { name: 'Сельдь солёная', calories: 217, protein: 17, fats: 16, carbs: 0 },
  // Яйца и молочное
  { name: 'Яйцо куриное', calories: 155, protein: 13, fats: 11, carbs: 1.1 },
  { name: 'Яичный белок', calories: 52, protein: 11, fats: 0.2, carbs: 0.7 },
  { name: 'Творог 0%', calories: 71, protein: 16, fats: 0, carbs: 1.8 },
  { name: 'Творог 5%', calories: 121, protein: 17, fats: 5, carbs: 1.8 },
  { name: 'Творог 9%', calories: 159, protein: 16, fats: 9, carbs: 2 },
  { name: 'Греческий йогурт', calories: 59, protein: 10, fats: 0.4, carbs: 3.6 },
  { name: 'Йогурт 2.5%', calories: 53, protein: 4.3, fats: 2.5, carbs: 3.5 },
  { name: 'Кефир 1%', calories: 40, protein: 3.3, fats: 1, carbs: 4.7 },
  { name: 'Ряженка 2.5%', calories: 54, protein: 2.9, fats: 2.5, carbs: 4.2 },
  { name: 'Молоко 3.2%', calories: 60, protein: 3.2, fats: 3.2, carbs: 4.7 },
  { name: 'Сметана 15%', calories: 158, protein: 2.6, fats: 15, carbs: 3 },
  { name: 'Сыр твёрдый', calories: 356, protein: 26, fats: 27, carbs: 0.4 },
  { name: 'Сыр плавленый', calories: 261, protein: 16, fats: 20, carbs: 3 },
  { name: 'Протеин (сывороточный)', calories: 380, protein: 74, fats: 5, carbs: 10 },
  // Крупы и злаки
  { name: 'Гречка (варёная)', calories: 110, protein: 4.2, fats: 0.6, carbs: 21 },
  { name: 'Гречка (сухая)', calories: 313, protein: 12, fats: 3.3, carbs: 57 },
  { name: 'Рис (варёный)', calories: 130, protein: 2.7, fats: 0.3, carbs: 28 },
  { name: 'Овсянка (варёная)', calories: 68, protein: 2.4, fats: 1.4, carbs: 12 },
  { name: 'Овсяные хлопья (сухие)', calories: 352, protein: 12, fats: 6, carbs: 60 },
  { name: 'Перловка варёная', calories: 109, protein: 3.1, fats: 0.4, carbs: 22 },
  { name: 'Пшено варёное', calories: 90, protein: 3, fats: 0.7, carbs: 18 },
  { name: 'Макароны (варёные)', calories: 158, protein: 5.5, fats: 0.9, carbs: 31 },
  // Хлеб
  { name: 'Хлеб цельнозерновой', calories: 247, protein: 8, fats: 2, carbs: 48 },
  { name: 'Хлеб чёрный (Бородинский)', calories: 201, protein: 6.8, fats: 1.3, carbs: 40 },
  { name: 'Батон белый', calories: 264, protein: 7.9, fats: 3.4, carbs: 50 },
  { name: 'Хлебцы рисовые', calories: 363, protein: 8, fats: 2.8, carbs: 76 },
  // Бобовые
  { name: 'Нут варёный', calories: 164, protein: 9, fats: 2.6, carbs: 27 },
  { name: 'Чечевица варёная', calories: 116, protein: 9, fats: 0.4, carbs: 20 },
  { name: 'Фасоль варёная', calories: 127, protein: 8.7, fats: 0.5, carbs: 22 },
  // Овощи
  { name: 'Картофель (варёный)', calories: 87, protein: 1.9, fats: 0.1, carbs: 20 },
  { name: 'Брокколи', calories: 34, protein: 2.8, fats: 0.4, carbs: 6.6 },
  { name: 'Капуста белокочанная', calories: 27, protein: 1.8, fats: 0.1, carbs: 4.7 },
  { name: 'Огурец', calories: 15, protein: 0.8, fats: 0.1, carbs: 2.5 },
  { name: 'Помидор', calories: 20, protein: 0.9, fats: 0.2, carbs: 3.9 },
  { name: 'Морковь', calories: 41, protein: 0.9, fats: 0.2, carbs: 9.6 },
  { name: 'Свекла (варёная)', calories: 49, protein: 1.8, fats: 0.1, carbs: 10 },
  { name: 'Шпинат', calories: 23, protein: 2.9, fats: 0.4, carbs: 3.6 },
  // Фрукты
  { name: 'Банан', calories: 89, protein: 1.1, fats: 0.3, carbs: 23 },
  { name: 'Яблоко', calories: 52, protein: 0.3, fats: 0.2, carbs: 14 },
  { name: 'Апельсин', calories: 47, protein: 0.9, fats: 0.1, carbs: 12 },
  { name: 'Клубника', calories: 32, protein: 0.7, fats: 0.3, carbs: 7.7 },
  { name: 'Вишня', calories: 52, protein: 0.8, fats: 0.5, carbs: 12 },
  // Орехи и масла
  { name: 'Орехи грецкие', calories: 654, protein: 15, fats: 65, carbs: 14 },
  { name: 'Миндаль', calories: 579, protein: 21, fats: 50, carbs: 22 },
  { name: 'Арахисовая паста', calories: 588, protein: 25, fats: 50, carbs: 20 },
  { name: 'Семечки подсолнечника', calories: 584, protein: 21, fats: 53, carbs: 11 },
  { name: 'Авокадо', calories: 160, protein: 2, fats: 15, carbs: 9 },
  { name: 'Оливковое масло', calories: 884, protein: 0, fats: 100, carbs: 0 },
  { name: 'Подсолнечное масло', calories: 884, protein: 0, fats: 100, carbs: 0 },
  // Прочее
  { name: 'Мёд', calories: 304, protein: 0.8, fats: 0, carbs: 82 },
  { name: 'Шоколад тёмный 70%', calories: 598, protein: 7.8, fats: 43, carbs: 46 },
  { name: 'Шоколад молочный', calories: 550, protein: 6.9, fats: 35, carbs: 52 },
  // Спортивное питание
  { name: 'Протеин казеиновый', calories: 370, protein: 76, fats: 4, carbs: 6 },
  { name: 'Гейнер', calories: 380, protein: 20, fats: 3, carbs: 70 },
  { name: 'Протеиновый батончик', calories: 370, protein: 30, fats: 12, carbs: 35 },
  { name: 'Изолят сывороточного белка', calories: 360, protein: 85, fats: 1, carbs: 5 },
  { name: 'Яичный протеин', calories: 365, protein: 78, fats: 2, carbs: 7 },
  // Готовые блюда
  { name: 'Куриная грудка варёная', calories: 137, protein: 27, fats: 3, carbs: 0 },
  { name: 'Куриная грудка запечённая', calories: 167, protein: 28, fats: 5, carbs: 1 },
  { name: 'Куриная грудка тушёная', calories: 144, protein: 26, fats: 4, carbs: 1 },
  { name: 'Котлета домашняя', calories: 230, protein: 15, fats: 16, carbs: 8 },
  { name: 'Пельмени варёные', calories: 245, protein: 11, fats: 10, carbs: 29 },
  { name: 'Борщ (без сметаны)', calories: 50, protein: 2, fats: 2, carbs: 6 },
  { name: 'Борщ со сметаной', calories: 58, protein: 2.5, fats: 3.2, carbs: 5.5 },
  { name: 'Гречка с куриной грудкой', calories: 130, protein: 14, fats: 2, carbs: 15 },
  { name: 'Рис с курицей', calories: 140, protein: 13, fats: 2.5, carbs: 17 },
  { name: 'Овсянка с бананом', calories: 110, protein: 3.5, fats: 2, carbs: 21 },
  // Молочные продукты и снеки
  { name: 'Сырок творожный глазированный', calories: 330, protein: 8, fats: 20, carbs: 29 },
  { name: 'Мороженое пломбир', calories: 230, protein: 3.5, fats: 12, carbs: 27 },
  { name: 'Кефир 2.5%', calories: 53, protein: 3.2, fats: 2.5, carbs: 4.1 },
  { name: 'Хлебцы гречневые', calories: 330, protein: 12, fats: 3, carbs: 64 },
  { name: 'Зефир', calories: 304, protein: 0.8, fats: 0, carbs: 77 },
  { name: 'Финики', calories: 277, protein: 1.8, fats: 0.2, carbs: 75 },
  { name: 'Курага', calories: 241, protein: 3.4, fats: 0.4, carbs: 60 },
  { name: 'Чернослив', calories: 240, protein: 2.3, fats: 0.7, carbs: 57 },
  // Напитки
  { name: 'Молоко 1.5%', calories: 46, protein: 3, fats: 1.5, carbs: 4.7 },
  { name: 'Апельсиновый сок', calories: 45, protein: 0.7, fats: 0.2, carbs: 10 },
  { name: 'Яблочный сок', calories: 46, protein: 0.5, fats: 0.1, carbs: 11 },
  { name: 'Томатный сок', calories: 21, protein: 1, fats: 0.1, carbs: 4.2 },
  // Дополнительные продукты
  { name: 'Тыква варёная', calories: 22, protein: 1, fats: 0.1, carbs: 4.4 },
  { name: 'Кабачок варёный', calories: 24, protein: 0.7, fats: 0.3, carbs: 4.6 },
  { name: 'Перец болгарский', calories: 27, protein: 0.9, fats: 0.3, carbs: 6 },
  { name: 'Цветная капуста варёная', calories: 29, protein: 2.3, fats: 0.3, carbs: 5 },
  { name: 'Кальмар варёный', calories: 110, protein: 22, fats: 1.2, carbs: 2 },
  { name: 'Семга слабосолёная', calories: 202, protein: 21, fats: 13, carbs: 0 },
  { name: 'Сардины в масле (консервы)', calories: 208, protein: 20, fats: 14, carbs: 0 },
  { name: 'Рис бурый варёный', calories: 111, protein: 2.6, fats: 0.9, carbs: 23 },
  { name: 'Картофельное пюре', calories: 90, protein: 2, fats: 3, carbs: 14 },
  { name: 'Омлет (2 яйца)', calories: 154, protein: 11, fats: 12, carbs: 1.5 },
  { name: 'Суп куриный с лапшой', calories: 40, protein: 3, fats: 1.5, carbs: 4 },
  { name: 'Запеканка творожная', calories: 185, protein: 14, fats: 8, carbs: 15 },
  { name: 'Кукурузная каша', calories: 86, protein: 2.5, fats: 0.5, carbs: 18 },
  { name: 'Тофу', calories: 76, protein: 8, fats: 4.8, carbs: 1.9 },
  { name: 'Чечевичный суп', calories: 63, protein: 4, fats: 1.5, carbs: 9 },
  { name: 'Оливки', calories: 145, protein: 1, fats: 15, carbs: 3.8 },
  { name: 'Майонез', calories: 680, protein: 2.8, fats: 74, carbs: 2.6 },
  { name: 'Кетчуп', calories: 93, protein: 1.8, fats: 0.1, carbs: 22 },
  { name: 'Сметана 20%', calories: 206, protein: 2.8, fats: 20, carbs: 3.2 },
  { name: 'Сыр Моцарелла', calories: 280, protein: 22, fats: 21, carbs: 2.2 },
  { name: 'Сыр Рикотта', calories: 174, protein: 11, fats: 13, carbs: 3 },
  { name: 'Грибы шампиньоны', calories: 27, protein: 4.3, fats: 1, carbs: 1 },
  { name: 'Чеснок', calories: 149, protein: 6.4, fats: 0.5, carbs: 33 },
  { name: 'Лук репчатый', calories: 41, protein: 1.1, fats: 0.1, carbs: 8.5 },
  // Фрукты и ягоды (дополнительные)
  { name: 'Виноград', calories: 67, protein: 0.6, fats: 0.2, carbs: 17 },
  { name: 'Арбуз', calories: 27, protein: 0.7, fats: 0.1, carbs: 6.8 },
  { name: 'Дыня', calories: 33, protein: 0.8, fats: 0.1, carbs: 7.7 },
  { name: 'Мандарин', calories: 40, protein: 0.8, fats: 0.2, carbs: 9.2 },
  { name: 'Груша', calories: 42, protein: 0.4, fats: 0.3, carbs: 11 },
  { name: 'Персик', calories: 39, protein: 0.9, fats: 0.1, carbs: 9.5 },
  { name: 'Черника', calories: 44, protein: 0.7, fats: 0.5, carbs: 10 },
  { name: 'Малина', calories: 46, protein: 1.2, fats: 0.8, carbs: 9 },
  { name: 'Голубика', calories: 57, protein: 0.7, fats: 0.3, carbs: 14 },
  { name: 'Гранат', calories: 83, protein: 1.7, fats: 1.2, carbs: 19 },
  { name: 'Манго', calories: 60, protein: 0.8, fats: 0.4, carbs: 15 },
  { name: 'Ананас', calories: 50, protein: 0.5, fats: 0.1, carbs: 13 },
  { name: 'Киви', calories: 61, protein: 1.1, fats: 0.5, carbs: 14 },
  // Овощи (дополнительные)
  { name: 'Батат (варёный)', calories: 86, protein: 2, fats: 0.1, carbs: 20 },
  { name: 'Спаржа', calories: 20, protein: 2.2, fats: 0.1, carbs: 3.9 },
  { name: 'Сельдерей', calories: 16, protein: 0.7, fats: 0.1, carbs: 3.6 },
  { name: 'Редис', calories: 20, protein: 1.2, fats: 0.1, carbs: 3.4 },
  { name: 'Кукуруза варёная', calories: 123, protein: 4, fats: 2.4, carbs: 22 },
  { name: 'Горошек зелёный', calories: 82, protein: 5.4, fats: 0.4, carbs: 14 },
  { name: 'Баклажан', calories: 24, protein: 1.2, fats: 0.1, carbs: 5.5 },
  // Зерновые и хлеб (дополнительные)
  { name: 'Лаваш армянский', calories: 277, protein: 9, fats: 1.1, carbs: 58 },
  { name: 'Киноа варёная', calories: 120, protein: 4.4, fats: 1.9, carbs: 21 },
  { name: 'Булгур варёный', calories: 83, protein: 3, fats: 0.2, carbs: 18 },
  { name: 'Овсяноблин', calories: 140, protein: 10, fats: 5, carbs: 14 },
  // Молочные (дополнительные)
  { name: 'Творожный сыр (рикотта/крем-чиз)', calories: 260, protein: 7, fats: 24, carbs: 3.2 },
  { name: 'Пармезан', calories: 392, protein: 36, fats: 26, carbs: 0 },
  { name: 'Брынза', calories: 260, protein: 17, fats: 20, carbs: 0.5 },
  { name: 'Молоко 2.5%', calories: 54, protein: 2.9, fats: 2.5, carbs: 4.7 },
  // Напитки (дополнительные)
  { name: 'Кофе с молоком', calories: 38, protein: 1.8, fats: 1.9, carbs: 3.7 },
  { name: 'Зелёный чай', calories: 2, protein: 0, fats: 0, carbs: 0 },
  // Рыба (дополнительные)
  { name: 'Тунец в собственном соку', calories: 99, protein: 23, fats: 0.5, carbs: 0 },
  { name: 'Креветки варёные', calories: 99, protein: 21, fats: 1.1, carbs: 0 },
  { name: 'Карп запечённый', calories: 121, protein: 18, fats: 5, carbs: 0 },
  // Готовые блюда и фастфуд
  { name: 'Сырники (2 шт)', calories: 220, protein: 14, fats: 9, carbs: 22 },
  { name: 'Блины (2 шт)', calories: 180, protein: 6, fats: 7, carbs: 24 },
  { name: 'Вареники с картошкой', calories: 195, protein: 6, fats: 4, carbs: 34 },
  { name: 'Салат Цезарь', calories: 180, protein: 9, fats: 13, carbs: 8 },
  { name: 'Оливье', calories: 198, protein: 6, fats: 15, carbs: 12 },
  { name: 'Пицца (1 кусок, 100г)', calories: 270, protein: 12, fats: 12, carbs: 30 },
  { name: 'Шашлык из свинины', calories: 218, protein: 19, fats: 15, carbs: 2 },
  { name: 'Шашлык из курицы', calories: 158, protein: 24, fats: 7, carbs: 0 },
  { name: 'Котлета рыбная', calories: 165, protein: 16, fats: 9, carbs: 6 },
  { name: 'Роллы (Калифорния, 100г)', calories: 146, protein: 7, fats: 4.5, carbs: 20 },
  // Колбасные изделия
  { name: 'Сосиски молочные', calories: 266, protein: 12, fats: 24, carbs: 1.8 },
  { name: 'Сардельки', calories: 332, protein: 11, fats: 31, carbs: 1.4 },
  // Молочные (дополнительные)
  { name: 'Сыр Гауда', calories: 356, protein: 25, fats: 28, carbs: 2.2 },
  { name: 'Сыр Чеддер', calories: 402, protein: 23, fats: 34, carbs: 1.3 },
  { name: 'Сыр Фета', calories: 264, protein: 14, fats: 21, carbs: 4.1 },
  // Напитки
  { name: 'Молочный коктейль', calories: 85, protein: 3.4, fats: 2.5, carbs: 12 },
  { name: 'Компот (без сахара)', calories: 30, protein: 0.2, fats: 0.1, carbs: 7 },
  // Яйца (способы приготовления)
  { name: 'Яйцо варёное вкрутую', calories: 155, protein: 13, fats: 11, carbs: 1.1 },
  { name: 'Яйцо варёное всмятку', calories: 143, protein: 13, fats: 10, carbs: 0.7 },
  // Сладкое
  { name: 'Печенье овсяное', calories: 437, protein: 6, fats: 18, carbs: 63 },
  // Супы (средняя порция 250г)
  { name: 'Борщ (250г)', calories: 68, protein: 3, fats: 3, carbs: 7 },
  { name: 'Щи (250г)', calories: 48, protein: 2.5, fats: 2.2, carbs: 5 },
  { name: 'Куриный суп (250г)', calories: 52, protein: 5, fats: 2, carbs: 4 },
  { name: 'Гречневый суп (250г)', calories: 60, protein: 3.5, fats: 2, carbs: 7 },
  { name: 'Рассольник (250г)', calories: 55, protein: 3, fats: 2.5, carbs: 6 },
  { name: 'Уха (250г)', calories: 45, protein: 6, fats: 1.5, carbs: 3 },
  // Каши (приготовленные)
  { name: 'Манная каша на молоке', calories: 100, protein: 3.3, fats: 2.5, carbs: 16 },
  { name: 'Ячневая каша', calories: 88, protein: 2.5, fats: 0.4, carbs: 19 },
  // Мясные блюда
  { name: 'Манты (1 шт)', calories: 180, protein: 9, fats: 8, carbs: 19 },
  { name: 'Бефстроганов', calories: 175, protein: 16, fats: 11, carbs: 4 },
  { name: 'Голубцы в соусе', calories: 135, protein: 10, fats: 7, carbs: 10 },
  { name: 'Котлета говяжья', calories: 220, protein: 17, fats: 14, carbs: 7 },
  { name: 'Ростбиф', calories: 190, protein: 28, fats: 9, carbs: 0 },
  { name: 'Гамбургер (булочка+котлета)', calories: 295, protein: 17, fats: 14, carbs: 24 },
  // Салаты (100г)
  { name: 'Греческий салат', calories: 74, protein: 2.4, fats: 5.5, carbs: 5 },
  { name: 'Капустный салат', calories: 40, protein: 1.5, fats: 2, carbs: 5 },
  { name: 'Морковь по-корейски', calories: 112, protein: 1.3, fats: 7, carbs: 11 },
  { name: 'Свёкла варёная с чесноком', calories: 65, protein: 1.8, fats: 2.5, carbs: 9 },
  // Орехи и семечки
  { name: 'Арахис', calories: 567, protein: 26, fats: 49, carbs: 16 },
  { name: 'Кунжут', calories: 573, protein: 18, fats: 50, carbs: 23 },
  { name: 'Тыквенные семечки', calories: 559, protein: 30, fats: 49, carbs: 11 },
  { name: 'Подсолнечные семечки', calories: 601, protein: 21, fats: 53, carbs: 20 },
  { name: 'Фундук', calories: 628, protein: 15, fats: 61, carbs: 17 },
  // Бобовые
  { name: 'Эдамаме (соевые бобы)', calories: 121, protein: 11, fats: 5, carbs: 9 },
  // Дополнительные фрукты
  { name: 'Грейпфрут', calories: 42, protein: 0.8, fats: 0.1, carbs: 10 },
  { name: 'Слива', calories: 46, protein: 0.7, fats: 0.3, carbs: 11 },
  { name: 'Хурма', calories: 67, protein: 0.5, fats: 0.4, carbs: 16 },
  // Хлебцы и снэки
  { name: 'Крекеры цельнозерновые', calories: 400, protein: 10, fats: 10, carbs: 70 },
  { name: 'Чипсы картофельные', calories: 536, protein: 7, fats: 30, carbs: 62 },
  // Соусы и заправки
  { name: 'Арахисовое масло', calories: 588, protein: 25, fats: 50, carbs: 20 },
  { name: 'Томатная паста', calories: 82, protein: 4.8, fats: 0.5, carbs: 17 },
  // Хлебобулочные
  { name: 'Батон нарезной', calories: 262, protein: 8, fats: 3.3, carbs: 49 },
  { name: 'Рогалик', calories: 315, protein: 9, fats: 9, carbs: 51 },
  // Прочие популярные продукты
  { name: 'Лапша быстрого приготовления', calories: 363, protein: 8, fats: 14, carbs: 52 },
  { name: 'Пельмени замороженные', calories: 197, protein: 9, fats: 7, carbs: 25 },
  { name: 'Шоколад горький (70%)', calories: 547, protein: 8, fats: 35, carbs: 52 },
  { name: 'Варенье', calories: 268, protein: 0.3, fats: 0.1, carbs: 70 },
  // Рыба и морепродукты (дополнительные)
  { name: 'Форель', calories: 148, protein: 20, fats: 7, carbs: 0 },
  { name: 'Сёмга запечённая', calories: 196, protein: 24, fats: 11, carbs: 0 },
  { name: 'Шпроты в масле', calories: 363, protein: 18, fats: 32, carbs: 0 },
  { name: 'Икра красная', calories: 251, protein: 32, fats: 14, carbs: 0 },
  { name: 'Морская капуста', calories: 5, protein: 0.6, fats: 0.1, carbs: 0.7 },
  { name: 'Мидии варёные', calories: 86, protein: 12, fats: 2, carbs: 3.7 },
  // Мясо и птица (дополнительные)
  { name: 'Курица жареная', calories: 238, protein: 25, fats: 15, carbs: 0 },
  { name: 'Утка запечённая', calories: 308, protein: 22, fats: 24, carbs: 0 },
  { name: 'Кролик тушёный', calories: 179, protein: 21, fats: 9, carbs: 3 },
  { name: 'Печень куриная', calories: 138, protein: 19, fats: 5, carbs: 3 },
  { name: 'Печень говяжья', calories: 127, protein: 20, fats: 3.7, carbs: 4.2 },
  // Овощи (дополнительные)
  { name: 'Цветная капуста', calories: 30, protein: 2.5, fats: 0.3, carbs: 5 },
  { name: 'Кабачок', calories: 24, protein: 0.7, fats: 0.3, carbs: 5 },
  { name: 'Тыква', calories: 26, protein: 1, fats: 0.1, carbs: 6 },
  { name: 'Болгарский перец красный', calories: 31, protein: 1, fats: 0.3, carbs: 6 },
  { name: 'Артишок', calories: 47, protein: 3.3, fats: 0.2, carbs: 11 },
  // Молочное (дополнительные)
  { name: 'Творожная масса с изюмом', calories: 257, protein: 8, fats: 9, carbs: 38 },
  { name: 'Ряженка 4%', calories: 67, protein: 2.8, fats: 4, carbs: 4.9 },
  { name: 'Масло сливочное', calories: 748, protein: 0.8, fats: 82, carbs: 0.8 },
  // Фрукты и ягоды (дополнительные)
  { name: 'Нектарин', calories: 44, protein: 1, fats: 0.3, carbs: 10 },
  { name: 'Абрикос', calories: 44, protein: 0.9, fats: 0.3, carbs: 10 },
  // Напитки (дополнительные)
  { name: 'Какао на молоке', calories: 92, protein: 4.5, fats: 3.5, carbs: 11 },
  { name: 'Кефир 3.2%', calories: 59, protein: 2.9, fats: 3.2, carbs: 3.8 },
  // Снэки и фастфуд
  { name: 'Горсть орехов (30г)', calories: 183, protein: 5, fats: 17, carbs: 6 },
  { name: 'Шаурма куриная', calories: 210, protein: 14, fats: 10, carbs: 18 },
  { name: 'Блин (1 шт, 50г)', calories: 108, protein: 3, fats: 4, carbs: 15 },
  { name: 'Сырник творожный', calories: 220, protein: 12, fats: 10, carbs: 22 },
  { name: 'Оладьи', calories: 205, protein: 7, fats: 9, carbs: 26 },

  // ─── Массовое расширение: русская кухня ─────────────────────────────────
  { name: 'Пирожок с капустой (жареный)', calories: 230, protein: 5, fats: 10, carbs: 31 },
  { name: 'Пирожок с картошкой', calories: 245, protein: 5, fats: 11, carbs: 32 },
  { name: 'Пирожок с мясом', calories: 270, protein: 9, fats: 12, carbs: 31 },
  { name: 'Пирожок с яйцом и луком', calories: 215, protein: 6, fats: 8, carbs: 30 },
  { name: 'Пирожок с рисом и яйцом', calories: 235, protein: 6, fats: 8, carbs: 35 },
  { name: 'Пирожок с повидлом', calories: 260, protein: 4, fats: 7, carbs: 45 },
  { name: 'Ватрушка с творогом', calories: 276, protein: 8, fats: 9, carbs: 42 },
  { name: 'Беляш с мясом', calories: 290, protein: 10, fats: 16, carbs: 25 },
  { name: 'Чебурек с мясом', calories: 265, protein: 9, fats: 15, carbs: 23 },
  { name: 'Расстегай с рыбой', calories: 245, protein: 12, fats: 10, carbs: 26 },
  { name: 'Кулебяка с мясом', calories: 260, protein: 11, fats: 12, carbs: 28 },
  { name: 'Ушки с мясом', calories: 225, protein: 9, fats: 9, carbs: 27 },
  { name: 'Солянка мясная (250г)', calories: 70, protein: 5, fats: 4, carbs: 4 },
  { name: 'Солянка рыбная (250г)', calories: 55, protein: 5, fats: 3, carbs: 3 },
  { name: 'Окрошка на квасе', calories: 55, protein: 3, fats: 3, carbs: 5 },
  { name: 'Холодец', calories: 115, protein: 19, fats: 4, carbs: 0.1 },
  { name: 'Студень говяжий', calories: 175, protein: 16, fats: 12, carbs: 0.1 },
  { name: 'Заливная рыба', calories: 85, protein: 12, fats: 3, carbs: 2 },
  { name: 'Жюльен с грибами', calories: 170, protein: 7, fats: 12, carbs: 7 },
  { name: 'Жюльен с курицей', calories: 190, protein: 10, fats: 14, carbs: 6 },
  { name: 'Селёдка под шубой', calories: 205, protein: 6, fats: 16, carbs: 10 },
  { name: 'Винегрет', calories: 76, protein: 1.5, fats: 4.5, carbs: 8 },
  { name: 'Салат мимоза', calories: 180, protein: 8, fats: 14, carbs: 6 },
  { name: 'Салат крабовый', calories: 165, protein: 6, fats: 12, carbs: 7 },
  { name: 'Пюре гороховое', calories: 115, protein: 7, fats: 2, carbs: 19 },
  { name: 'Икра кабачковая', calories: 97, protein: 1.3, fats: 7, carbs: 7 },
  { name: 'Икра баклажанная', calories: 148, protein: 1.7, fats: 13, carbs: 7 },
  { name: 'Голубцы с мясом', calories: 142, protein: 9, fats: 8, carbs: 9 },
  { name: 'Фаршированный перец', calories: 110, protein: 7, fats: 5, carbs: 9 },
  { name: 'Курник', calories: 235, protein: 13, fats: 14, carbs: 15 },
  { name: 'Шарлотка яблочная', calories: 235, protein: 5, fats: 7, carbs: 38 },
  { name: 'Запеканка рисовая', calories: 145, protein: 5, fats: 5, carbs: 20 },
  { name: 'Запеканка вермишелевая', calories: 195, protein: 7, fats: 7, carbs: 26 },
  { name: 'Плов с бараниной', calories: 195, protein: 9, fats: 9, carbs: 20 },
  { name: 'Плов с курицей', calories: 175, protein: 9, fats: 7, carbs: 20 },
  { name: 'Плов с говядиной', calories: 185, protein: 9, fats: 8, carbs: 20 },
  { name: 'Каша пшённая на молоке', calories: 124, protein: 3.5, fats: 4, carbs: 19 },
  { name: 'Каша рисовая на молоке', calories: 97, protein: 2.7, fats: 2, carbs: 17 },
  { name: 'Каша овсяная на молоке', calories: 102, protein: 3.4, fats: 4, carbs: 14 },
  { name: 'Каша гречневая на молоке', calories: 118, protein: 4.5, fats: 4, carbs: 17 },
  { name: 'Молочный суп с вермишелью', calories: 78, protein: 3, fats: 2.5, carbs: 11 },
  { name: 'Суп гороховый (250г)', calories: 65, protein: 4, fats: 2, carbs: 8 },
  { name: 'Суп-лапша куриная (250г)', calories: 52, protein: 3.5, fats: 1.5, carbs: 6 },
  { name: 'Грибной суп (250г)', calories: 40, protein: 1.5, fats: 2, carbs: 4 },
  { name: 'Суп-пюре из шампиньонов', calories: 85, protein: 2.5, fats: 6, carbs: 5 },
  { name: 'Суп-пюре тыквенный', calories: 70, protein: 1.5, fats: 4, carbs: 7 },
  { name: 'Суп-пюре брокколи', calories: 80, protein: 3, fats: 5, carbs: 6 },

  // ─── Кавказская и среднеазиатская кухня ────────────────────────────────
  { name: 'Хинкали (1 шт)', calories: 130, protein: 6, fats: 6, carbs: 13 },
  { name: 'Хачапури по-аджарски', calories: 290, protein: 12, fats: 14, carbs: 30 },
  { name: 'Хачапури по-имеретински', calories: 260, protein: 11, fats: 11, carbs: 29 },
  { name: 'Лобио', calories: 110, protein: 7, fats: 4, carbs: 14 },
  { name: 'Лагман', calories: 115, protein: 7, fats: 5, carbs: 12 },
  { name: 'Шурпа', calories: 85, protein: 5, fats: 4.5, carbs: 6 },
  { name: 'Чебурек жареный', calories: 265, protein: 9, fats: 15, carbs: 23 },
  { name: 'Самса с мясом', calories: 310, protein: 10, fats: 18, carbs: 28 },
  { name: 'Самса с тыквой', calories: 245, protein: 5, fats: 12, carbs: 31 },
  { name: 'Долма', calories: 155, protein: 7, fats: 8, carbs: 14 },
  { name: 'Шашлык из баранины', calories: 285, protein: 22, fats: 22, carbs: 0 },
  { name: 'Люля-кебаб бараний', calories: 275, protein: 18, fats: 22, carbs: 2 },
  { name: 'Люля-кебаб куриный', calories: 165, protein: 18, fats: 10, carbs: 2 },
  { name: 'Харчо (250г)', calories: 80, protein: 5, fats: 4, carbs: 6 },
  { name: 'Чахохбили', calories: 145, protein: 13, fats: 9, carbs: 4 },
  { name: 'Сациви', calories: 215, protein: 14, fats: 17, carbs: 3 },
  { name: 'Чурчхела', calories: 410, protein: 5, fats: 16, carbs: 61 },
  { name: 'Пахлава', calories: 450, protein: 7, fats: 25, carbs: 49 },
  { name: 'Бешбармак', calories: 200, protein: 13, fats: 11, carbs: 14 },

  // ─── Итальянская кухня ──────────────────────────────────────────────────
  { name: 'Паста Карбонара', calories: 260, protein: 11, fats: 12, carbs: 27 },
  { name: 'Паста Болоньезе', calories: 180, protein: 9, fats: 6, carbs: 22 },
  { name: 'Паста с песто', calories: 210, protein: 7, fats: 11, carbs: 22 },
  { name: 'Спагетти с томатным соусом', calories: 140, protein: 5, fats: 2, carbs: 26 },
  { name: 'Феттучине Альфредо', calories: 240, protein: 8, fats: 14, carbs: 22 },
  { name: 'Равиоли с сыром', calories: 225, protein: 9, fats: 9, carbs: 27 },
  { name: 'Лазанья', calories: 195, protein: 11, fats: 10, carbs: 15 },
  { name: 'Ризотто с грибами', calories: 155, protein: 4, fats: 5, carbs: 23 },
  { name: 'Ризотто с морепродуктами', calories: 170, protein: 7, fats: 5, carbs: 24 },
  { name: 'Пицца Маргарита', calories: 240, protein: 11, fats: 9, carbs: 29 },
  { name: 'Пицца Пепперони', calories: 290, protein: 12, fats: 14, carbs: 30 },
  { name: 'Пицца 4 сыра', calories: 310, protein: 14, fats: 17, carbs: 26 },
  { name: 'Пицца Гавайская', calories: 260, protein: 11, fats: 10, carbs: 31 },
  { name: 'Пицца Мясная', calories: 305, protein: 15, fats: 15, carbs: 28 },
  { name: 'Фокачча', calories: 270, protein: 6, fats: 9, carbs: 41 },
  { name: 'Брускетта с томатами', calories: 180, protein: 5, fats: 7, carbs: 25 },
  { name: 'Тирамису', calories: 285, protein: 5, fats: 18, carbs: 26 },
  { name: 'Панакотта', calories: 290, protein: 5, fats: 22, carbs: 19 },
  { name: 'Чиабатта', calories: 260, protein: 9, fats: 3, carbs: 51 },

  // ─── Японская кухня ─────────────────────────────────────────────────────
  { name: 'Роллы Филадельфия', calories: 180, protein: 7, fats: 8, carbs: 20 },
  { name: 'Роллы Калифорния', calories: 145, protein: 6, fats: 4.5, carbs: 21 },
  { name: 'Роллы Дракон', calories: 195, protein: 7, fats: 9, carbs: 21 },
  { name: 'Роллы Унаги', calories: 190, protein: 8, fats: 7, carbs: 23 },
  { name: 'Нигири с лососем (1 шт)', calories: 50, protein: 4, fats: 1.2, carbs: 6 },
  { name: 'Нигири с тунцом (1 шт)', calories: 45, protein: 5, fats: 0.3, carbs: 6 },
  { name: 'Нигири с креветкой (1 шт)', calories: 42, protein: 3, fats: 0.3, carbs: 7 },
  { name: 'Сашими из лосося', calories: 208, protein: 20, fats: 13, carbs: 0 },
  { name: 'Сашими из тунца', calories: 144, protein: 23, fats: 5, carbs: 0 },
  { name: 'Мисо-суп', calories: 40, protein: 3, fats: 1.5, carbs: 4 },
  { name: 'Суп Рамен с курицей', calories: 155, protein: 9, fats: 5, carbs: 19 },
  { name: 'Суп Рамен с говядиной', calories: 175, protein: 10, fats: 7, carbs: 18 },
  { name: 'Суп Удон', calories: 95, protein: 4, fats: 1.5, carbs: 17 },
  { name: 'Темпура из креветок', calories: 245, protein: 10, fats: 13, carbs: 22 },
  { name: 'Гёдза (1 шт)', calories: 45, protein: 2, fats: 2, carbs: 5 },
  { name: 'Якитори куриный', calories: 140, protein: 16, fats: 6, carbs: 5 },
  { name: 'Якисоба', calories: 175, protein: 7, fats: 6, carbs: 23 },
  { name: 'Соевый соус', calories: 53, protein: 8, fats: 0.1, carbs: 5 },
  { name: 'Васаби', calories: 109, protein: 4, fats: 0.6, carbs: 24 },
  { name: 'Имбирь маринованный', calories: 47, protein: 0.2, fats: 0.1, carbs: 10 },

  // ─── Китайская и тайская кухня ──────────────────────────────────────────
  { name: 'Лапша вок с курицей', calories: 165, protein: 10, fats: 5, carbs: 20 },
  { name: 'Лапша вок с говядиной', calories: 185, protein: 11, fats: 7, carbs: 20 },
  { name: 'Лапша вок с морепродуктами', calories: 145, protein: 10, fats: 4, carbs: 18 },
  { name: 'Курица в кисло-сладком соусе', calories: 220, protein: 12, fats: 10, carbs: 21 },
  { name: 'Утка по-пекински', calories: 340, protein: 20, fats: 27, carbs: 3 },
  { name: 'Жареный рис с курицей', calories: 175, protein: 8, fats: 5, carbs: 25 },
  { name: 'Димсам', calories: 185, protein: 9, fats: 7, carbs: 22 },
  { name: 'Том-ям с креветками', calories: 65, protein: 6, fats: 3, carbs: 4 },
  { name: 'Том-ям с курицей', calories: 75, protein: 7, fats: 4, carbs: 4 },
  { name: 'Пад-тай', calories: 215, protein: 9, fats: 7, carbs: 30 },
  { name: 'Карри с курицей', calories: 175, protein: 12, fats: 10, carbs: 10 },
  { name: 'Карри зелёный тайский', calories: 155, protein: 10, fats: 10, carbs: 8 },

  // ─── Индийская и ближневосточная кухня ─────────────────────────────────
  { name: 'Наан', calories: 295, protein: 9, fats: 5, carbs: 53 },
  { name: 'Самоса', calories: 260, protein: 6, fats: 15, carbs: 25 },
  { name: 'Курица Тикка Масала', calories: 165, protein: 14, fats: 10, carbs: 5 },
  { name: 'Курица Бирьяни', calories: 180, protein: 10, fats: 6, carbs: 22 },
  { name: 'Палак панир', calories: 145, protein: 8, fats: 10, carbs: 6 },
  { name: 'Далл', calories: 105, protein: 6, fats: 3, carbs: 14 },
  { name: 'Хумус', calories: 166, protein: 8, fats: 10, carbs: 14 },
  { name: 'Фалафель (1 шт)', calories: 55, protein: 2, fats: 3, carbs: 5 },
  { name: 'Фалафель в пите', calories: 225, protein: 8, fats: 12, carbs: 23 },
  { name: 'Шаурма в лаваше', calories: 220, protein: 12, fats: 10, carbs: 22 },
  { name: 'Донер-кебаб', calories: 235, protein: 15, fats: 10, carbs: 21 },
  { name: 'Гирос', calories: 240, protein: 13, fats: 12, carbs: 20 },
  { name: 'Табуле', calories: 120, protein: 3, fats: 5, carbs: 18 },
  { name: 'Баба гануш', calories: 125, protein: 2, fats: 9, carbs: 9 },
  { name: 'Долма в виноградных листьях', calories: 155, protein: 4, fats: 7, carbs: 19 },
  { name: 'Кебаб из баранины', calories: 250, protein: 18, fats: 18, carbs: 3 },
  { name: 'Кускус варёный', calories: 112, protein: 3.8, fats: 0.2, carbs: 23 },

  // ─── Мексиканская кухня ─────────────────────────────────────────────────
  { name: 'Буррито с курицей', calories: 235, protein: 10, fats: 8, carbs: 30 },
  { name: 'Буррито с говядиной', calories: 260, protein: 11, fats: 11, carbs: 29 },
  { name: 'Тако с курицей', calories: 205, protein: 9, fats: 10, carbs: 20 },
  { name: 'Кесадилья с сыром', calories: 265, protein: 11, fats: 13, carbs: 27 },
  { name: 'Начос с сыром', calories: 340, protein: 7, fats: 19, carbs: 36 },
  { name: 'Гуакамоле', calories: 157, protein: 2, fats: 14, carbs: 9 },
  { name: 'Сальса', calories: 36, protein: 1.5, fats: 0.2, carbs: 8 },
  { name: 'Чили кон карне', calories: 130, protein: 10, fats: 6, carbs: 10 },
  { name: 'Энчилада', calories: 210, protein: 10, fats: 11, carbs: 18 },
  { name: 'Фахитас', calories: 195, protein: 13, fats: 9, carbs: 17 },

  // ─── Фастфуд и сети ─────────────────────────────────────────────────────
  { name: 'Биг Мак', calories: 257, protein: 13, fats: 13, carbs: 21 },
  { name: 'Чизбургер', calories: 275, protein: 15, fats: 12, carbs: 27 },
  { name: 'Двойной чизбургер', calories: 280, protein: 17, fats: 14, carbs: 22 },
  { name: 'Чикен Бургер', calories: 250, protein: 12, fats: 11, carbs: 26 },
  { name: 'Воппер', calories: 265, protein: 13, fats: 15, carbs: 21 },
  { name: 'Фри большая (150г)', calories: 310, protein: 3.5, fats: 15, carbs: 40 },
  { name: 'Фри средняя (100г)', calories: 310, protein: 3.5, fats: 15, carbs: 40 },
  { name: 'Наггетсы куриные (6 шт)', calories: 260, protein: 14, fats: 15, carbs: 16 },
  { name: 'Крылья KFC (1 шт)', calories: 110, protein: 7, fats: 8, carbs: 3 },
  { name: 'Твистер KFC', calories: 240, protein: 11, fats: 11, carbs: 25 },
  { name: 'Боксмастер KFC', calories: 285, protein: 12, fats: 15, carbs: 26 },
  { name: 'Сабвей-сэндвич (30 см)', calories: 225, protein: 12, fats: 6, carbs: 32 },
  { name: 'Хот-дог классический', calories: 245, protein: 9, fats: 14, carbs: 21 },
  { name: 'Картофель по-деревенски', calories: 187, protein: 3.3, fats: 10, carbs: 22 },
  { name: 'Драники', calories: 180, protein: 3, fats: 10, carbs: 20 },
  { name: 'Луковые кольца', calories: 405, protein: 5, fats: 23, carbs: 45 },
  { name: 'Картошка фри мини', calories: 310, protein: 3, fats: 15, carbs: 41 },

  // ─── Американская / европейская кухня ──────────────────────────────────
  { name: 'Стейк рибай', calories: 271, protein: 25, fats: 19, carbs: 0 },
  { name: 'Стейк ти-бон', calories: 265, protein: 26, fats: 18, carbs: 0 },
  { name: 'Стейк филе-миньон', calories: 175, protein: 27, fats: 8, carbs: 0 },
  { name: 'Рёбрышки свиные', calories: 292, protein: 20, fats: 23, carbs: 0.5 },
  { name: 'Куриные стрипсы', calories: 230, protein: 20, fats: 11, carbs: 12 },
  { name: 'Крабовый суп', calories: 75, protein: 5, fats: 3, carbs: 7 },
  { name: 'Куриные крылышки в соусе', calories: 245, protein: 18, fats: 17, carbs: 4 },
  { name: 'Клаб-сэндвич', calories: 275, protein: 15, fats: 15, carbs: 20 },
  { name: 'Чизкейк', calories: 321, protein: 5, fats: 22, carbs: 26 },
  { name: 'Брауни', calories: 415, protein: 5, fats: 22, carbs: 51 },
  { name: 'Маффин черничный', calories: 295, protein: 5, fats: 12, carbs: 42 },
  { name: 'Маффин шоколадный', calories: 380, protein: 5, fats: 18, carbs: 50 },
  { name: 'Круассан', calories: 405, protein: 8, fats: 21, carbs: 46 },
  { name: 'Круассан с шоколадом', calories: 445, protein: 8, fats: 25, carbs: 48 },
  { name: 'Пончик глазированный', calories: 420, protein: 5, fats: 22, carbs: 51 },
  { name: 'Пончик с джемом', calories: 390, protein: 5, fats: 18, carbs: 54 },

  // ─── Сладости и десерты ─────────────────────────────────────────────────
  { name: 'Торт Наполеон', calories: 395, protein: 5, fats: 22, carbs: 44 },
  { name: 'Торт Медовик', calories: 378, protein: 6, fats: 21, carbs: 42 },
  { name: 'Торт Прага', calories: 422, protein: 6, fats: 27, carbs: 40 },
  { name: 'Торт Красный Бархат', calories: 365, protein: 5, fats: 19, carbs: 44 },
  { name: 'Торт Эстерхази', calories: 430, protein: 9, fats: 29, carbs: 35 },
  { name: 'Эклер с заварным кремом', calories: 272, protein: 7, fats: 15, carbs: 27 },
  { name: 'Профитроли', calories: 390, protein: 7, fats: 26, carbs: 31 },
  { name: 'Мороженое ванильное', calories: 207, protein: 3.5, fats: 11, carbs: 24 },
  { name: 'Мороженое шоколадное', calories: 216, protein: 4, fats: 11, carbs: 27 },
  { name: 'Мороженое фисташковое', calories: 225, protein: 5, fats: 13, carbs: 23 },
  { name: 'Мороженое сорбет', calories: 145, protein: 0.5, fats: 0, carbs: 36 },
  { name: 'Конфета шоколадная', calories: 500, protein: 6, fats: 30, carbs: 55 },
  { name: 'Трюфель шоколадный', calories: 530, protein: 7, fats: 36, carbs: 48 },
  { name: 'Пастила', calories: 310, protein: 0.5, fats: 0, carbs: 80 },
  { name: 'Халва подсолнечная', calories: 523, protein: 12, fats: 30, carbs: 54 },
  { name: 'Рахат-лукум', calories: 316, protein: 0.8, fats: 0.5, carbs: 79 },
  { name: 'Щербет', calories: 417, protein: 6, fats: 15, carbs: 66 },
  { name: 'Козинаки', calories: 530, protein: 13, fats: 30, carbs: 56 },
  { name: 'Пирожное картошка', calories: 382, protein: 5, fats: 18, carbs: 50 },
  { name: 'Макаронс (1 шт)', calories: 90, protein: 2, fats: 4, carbs: 12 },
  { name: 'Безе', calories: 365, protein: 3, fats: 0.5, carbs: 88 },
  { name: 'Торт-суфле птичье молоко', calories: 345, protein: 5, fats: 14, carbs: 52 },
  { name: 'Крем-брюле', calories: 290, protein: 4, fats: 22, carbs: 20 },

  // ─── Батончики и шоколад (брендированные) ──────────────────────────────
  { name: 'Сникерс (50г)', calories: 488, protein: 8.7, fats: 24, carbs: 57 },
  { name: 'Марс (50г)', calories: 449, protein: 4, fats: 17, carbs: 69 },
  { name: 'Баунти', calories: 490, protein: 4, fats: 26, carbs: 58 },
  { name: 'Твикс', calories: 492, protein: 5, fats: 24, carbs: 64 },
  { name: 'Киндер-шоколад', calories: 562, protein: 8.5, fats: 33, carbs: 56 },
  { name: 'Киндер-Сюрприз', calories: 570, protein: 8, fats: 36, carbs: 53 },
  { name: 'Баунти мини', calories: 490, protein: 4, fats: 26, carbs: 58 },
  { name: 'Аленка шоколад', calories: 550, protein: 7, fats: 34, carbs: 54 },
  { name: 'Алёнка молочная', calories: 549, protein: 7, fats: 34, carbs: 54 },
  { name: 'Раффаэлло (1 шт)', calories: 612, protein: 6, fats: 46, carbs: 44 },
  { name: 'Ферреро Роше (1 шт)', calories: 580, protein: 8, fats: 41, carbs: 45 },
  { name: 'Нутелла', calories: 539, protein: 6.3, fats: 31, carbs: 58 },
  { name: 'M&Ms', calories: 480, protein: 4.3, fats: 19, carbs: 70 },
  { name: 'Skittles', calories: 405, protein: 0.2, fats: 4.4, carbs: 91 },
  { name: 'Milky Way', calories: 453, protein: 3.6, fats: 17, carbs: 72 },
  { name: 'Picnic', calories: 500, protein: 8, fats: 26, carbs: 59 },

  // ─── Хлеб и выпечка (дополнительные) ────────────────────────────────────
  { name: 'Пита', calories: 275, protein: 9, fats: 1.2, carbs: 55 },
  { name: 'Багет', calories: 263, protein: 9, fats: 1, carbs: 50 },
  { name: 'Тортилья пшеничная', calories: 304, protein: 8, fats: 7, carbs: 50 },
  { name: 'Тортилья кукурузная', calories: 218, protein: 5.7, fats: 2.9, carbs: 45 },
  { name: 'Хлеб ржаной', calories: 165, protein: 4.7, fats: 0.7, carbs: 34 },
  { name: 'Хлеб безглютеновый', calories: 280, protein: 4, fats: 10, carbs: 44 },
  { name: 'Сухари ванильные', calories: 388, protein: 9, fats: 5, carbs: 74 },
  { name: 'Гренки со специями', calories: 390, protein: 8, fats: 12, carbs: 64 },
  { name: 'Куличи пасхальные', calories: 330, protein: 7, fats: 10, carbs: 54 },
  { name: 'Слойка с сыром', calories: 365, protein: 8, fats: 23, carbs: 30 },
  { name: 'Слойка с мясом', calories: 335, protein: 9, fats: 21, carbs: 28 },
  { name: 'Штрудель яблочный', calories: 240, protein: 3.5, fats: 9, carbs: 37 },
  { name: 'Чиабатта с оливками', calories: 275, protein: 8, fats: 6, carbs: 47 },

  // ─── Крупы и каши (дополнительно) ───────────────────────────────────────
  { name: 'Киноа сухая', calories: 368, protein: 14, fats: 6, carbs: 64 },
  { name: 'Булгур сухой', calories: 342, protein: 12, fats: 1.3, carbs: 76 },
  { name: 'Кускус сухой', calories: 376, protein: 13, fats: 0.6, carbs: 77 },
  { name: 'Полба варёная', calories: 120, protein: 5.5, fats: 0.8, carbs: 25 },
  { name: 'Амарант варёный', calories: 102, protein: 3.8, fats: 1.6, carbs: 19 },
  { name: 'Чиа семена', calories: 486, protein: 17, fats: 31, carbs: 42 },
  { name: 'Лён семена', calories: 534, protein: 18, fats: 42, carbs: 29 },
  { name: 'Конопляные семена', calories: 553, protein: 32, fats: 49, carbs: 9 },
  { name: 'Кускус с овощами', calories: 135, protein: 4, fats: 1, carbs: 26 },

  // ─── Молочные и альтернативы ────────────────────────────────────────────
  { name: 'Молоко миндальное', calories: 17, protein: 0.6, fats: 1.2, carbs: 0.6 },
  { name: 'Молоко соевое', calories: 54, protein: 3.3, fats: 1.8, carbs: 6 },
  { name: 'Молоко овсяное', calories: 43, protein: 1, fats: 1.5, carbs: 6.7 },
  { name: 'Молоко кокосовое', calories: 230, protein: 2.3, fats: 24, carbs: 3.5 },
  { name: 'Молоко рисовое', calories: 47, protein: 0.3, fats: 1, carbs: 9 },
  { name: 'Йогурт Активия натуральный', calories: 56, protein: 3.7, fats: 2.5, carbs: 4.4 },
  { name: 'Йогурт Данон', calories: 73, protein: 3.8, fats: 1.5, carbs: 11.5 },
  { name: 'Йогурт Чудо', calories: 99, protein: 2.8, fats: 2.5, carbs: 17 },
  { name: 'Йогурт греческий 2%', calories: 73, protein: 10, fats: 2, carbs: 3.6 },
  { name: 'Йогурт греческий 0%', calories: 59, protein: 10, fats: 0, carbs: 4 },
  { name: 'Йогурт питьевой', calories: 77, protein: 2.8, fats: 1.5, carbs: 13 },
  { name: 'Снежок', calories: 79, protein: 2.8, fats: 2.5, carbs: 11.9 },
  { name: 'Простокваша', calories: 58, protein: 2.9, fats: 3.2, carbs: 4.1 },
  { name: 'Творожный сыр Хохланд', calories: 260, protein: 7, fats: 24, carbs: 4 },
  { name: 'Сыр Филадельфия', calories: 253, protein: 5.4, fats: 24, carbs: 4 },
  { name: 'Сыр Маскарпоне', calories: 429, protein: 4.5, fats: 44, carbs: 4 },
  { name: 'Сыр Адыгейский', calories: 240, protein: 19, fats: 19, carbs: 1.5 },
  { name: 'Сыр Сулугуни', calories: 286, protein: 19, fats: 24, carbs: 0 },
  { name: 'Сыр Косичка', calories: 280, protein: 24, fats: 20, carbs: 1.5 },
  { name: 'Сыр Бри', calories: 291, protein: 21, fats: 23, carbs: 0.5 },
  { name: 'Сыр Камамбер', calories: 300, protein: 20, fats: 24, carbs: 0.5 },
  { name: 'Сыр Дор-блю', calories: 354, protein: 21, fats: 30, carbs: 0 },
  { name: 'Сыр Рокфор', calories: 369, protein: 22, fats: 31, carbs: 2 },

  // ─── Рыба и морепродукты (дополнительно) ───────────────────────────────
  { name: 'Дорадо запечённая', calories: 115, protein: 19, fats: 4, carbs: 0 },
  { name: 'Сибас запечённый', calories: 100, protein: 18, fats: 3, carbs: 0 },
  { name: 'Окунь морской', calories: 110, protein: 18, fats: 4, carbs: 0 },
  { name: 'Камбала', calories: 90, protein: 16, fats: 3, carbs: 0 },
  { name: 'Палтус', calories: 190, protein: 19, fats: 13, carbs: 0 },
  { name: 'Судак', calories: 84, protein: 19, fats: 1.1, carbs: 0 },
  { name: 'Щука', calories: 84, protein: 18, fats: 1.1, carbs: 0 },
  { name: 'Налим', calories: 81, protein: 18, fats: 0.6, carbs: 0 },
  { name: 'Хек', calories: 86, protein: 16, fats: 2.2, carbs: 0 },
  { name: 'Тилапия', calories: 96, protein: 20, fats: 1.7, carbs: 0 },
  { name: 'Акне зубатка', calories: 126, protein: 20, fats: 5, carbs: 0 },
  { name: 'Шпроты', calories: 363, protein: 17, fats: 32, carbs: 0 },
  { name: 'Килька', calories: 137, protein: 17, fats: 7.6, carbs: 0 },
  { name: 'Анчоус', calories: 135, protein: 20, fats: 6.1, carbs: 0 },
  { name: 'Устрицы', calories: 72, protein: 9, fats: 2, carbs: 5 },
  { name: 'Гребешки', calories: 88, protein: 17, fats: 1, carbs: 2.4 },
  { name: 'Краб варёный', calories: 97, protein: 19, fats: 1.5, carbs: 0 },
  { name: 'Крабовые палочки', calories: 88, protein: 9, fats: 1, carbs: 10 },
  { name: 'Осьминог варёный', calories: 82, protein: 15, fats: 1, carbs: 2 },
  { name: 'Икра чёрная', calories: 203, protein: 28, fats: 10, carbs: 4 },
  { name: 'Икра минтая', calories: 132, protein: 28, fats: 2, carbs: 1 },

  // ─── Мясо и птица (дополнительно) ──────────────────────────────────────
  { name: 'Бекон', calories: 417, protein: 23, fats: 37, carbs: 0 },
  { name: 'Грудинка копчёная', calories: 514, protein: 10, fats: 53, carbs: 0 },
  { name: 'Карбонад', calories: 200, protein: 24, fats: 10, carbs: 0 },
  { name: 'Ветчина варёная', calories: 270, protein: 23, fats: 20, carbs: 0 },
  { name: 'Ветчина копчёная', calories: 279, protein: 23, fats: 21, carbs: 0 },
  { name: 'Буженина', calories: 210, protein: 17, fats: 16, carbs: 0 },
  { name: 'Колбаса сырокопчёная', calories: 473, protein: 24, fats: 42, carbs: 0 },
  { name: 'Колбаса варёно-копчёная', calories: 402, protein: 17, fats: 37, carbs: 0 },
  { name: 'Салями', calories: 568, protein: 22, fats: 54, carbs: 1 },
  { name: 'Пепперони', calories: 494, protein: 23, fats: 44, carbs: 1.2 },
  { name: 'Сервелат', calories: 425, protein: 24, fats: 40, carbs: 0 },
  { name: 'Курица целая жареная', calories: 239, protein: 23, fats: 16, carbs: 0 },
  { name: 'Курица гриль', calories: 210, protein: 26, fats: 12, carbs: 0 },
  { name: 'Баранина отварная', calories: 293, protein: 22, fats: 23, carbs: 0 },
  { name: 'Баранина жареная', calories: 320, protein: 20, fats: 27, carbs: 0 },
  { name: 'Телятина отварная', calories: 131, protein: 30, fats: 1, carbs: 0 },
  { name: 'Телятина жареная', calories: 172, protein: 27, fats: 7, carbs: 0 },
  { name: 'Язык говяжий', calories: 231, protein: 16, fats: 18, carbs: 2 },
  { name: 'Сердце куриное', calories: 159, protein: 16, fats: 10, carbs: 1 },
  { name: 'Сердце говяжье', calories: 96, protein: 15, fats: 3.5, carbs: 0 },
  { name: 'Мозги говяжьи', calories: 124, protein: 11, fats: 8.6, carbs: 0 },
  { name: 'Почки говяжьи', calories: 86, protein: 13, fats: 2.8, carbs: 0 },
  { name: 'Желудок куриный', calories: 130, protein: 18, fats: 6, carbs: 0 },
  { name: 'Тушёнка говяжья', calories: 220, protein: 16, fats: 17, carbs: 0 },
  { name: 'Тушёнка свиная', calories: 350, protein: 13, fats: 33, carbs: 0 },

  // ─── Напитки алкогольные ────────────────────────────────────────────────
  { name: 'Пиво светлое 4%', calories: 42, protein: 0.6, fats: 0, carbs: 4 },
  { name: 'Пиво тёмное', calories: 48, protein: 0.5, fats: 0, carbs: 5 },
  { name: 'Пиво безалкогольное', calories: 26, protein: 0.3, fats: 0, carbs: 4.6 },
  { name: 'Вино красное сухое', calories: 68, protein: 0.2, fats: 0, carbs: 0.3 },
  { name: 'Вино белое сухое', calories: 66, protein: 0.1, fats: 0, carbs: 0.6 },
  { name: 'Вино полусладкое', calories: 88, protein: 0.1, fats: 0, carbs: 5 },
  { name: 'Шампанское брют', calories: 78, protein: 0.2, fats: 0, carbs: 1.5 },
  { name: 'Шампанское полусладкое', calories: 88, protein: 0.2, fats: 0, carbs: 5 },
  { name: 'Водка 40%', calories: 235, protein: 0, fats: 0, carbs: 0 },
  { name: 'Коньяк', calories: 240, protein: 0, fats: 0, carbs: 1.5 },
  { name: 'Виски', calories: 235, protein: 0, fats: 0, carbs: 0 },
  { name: 'Джин', calories: 220, protein: 0, fats: 0, carbs: 0 },
  { name: 'Ром', calories: 231, protein: 0, fats: 0, carbs: 0 },
  { name: 'Текила', calories: 231, protein: 0, fats: 0, carbs: 0 },
  { name: 'Ликёр Бейлис', calories: 327, protein: 3, fats: 13, carbs: 25 },
  { name: 'Мохито', calories: 90, protein: 0, fats: 0, carbs: 13 },
  { name: 'Маргарита', calories: 170, protein: 0.1, fats: 0, carbs: 11 },
  { name: 'Пина колада', calories: 220, protein: 0.5, fats: 6, carbs: 32 },
  { name: 'Джин-тоник', calories: 95, protein: 0, fats: 0, carbs: 8 },

  // ─── Напитки безалкогольные ─────────────────────────────────────────────
  { name: 'Coca-Cola', calories: 42, protein: 0, fats: 0, carbs: 10.6 },
  { name: 'Coca-Cola Zero', calories: 0.3, protein: 0, fats: 0, carbs: 0 },
  { name: 'Fanta', calories: 48, protein: 0, fats: 0, carbs: 12 },
  { name: 'Sprite', calories: 40, protein: 0, fats: 0, carbs: 10 },
  { name: 'Pepsi', calories: 43, protein: 0, fats: 0, carbs: 11 },
  { name: 'Lipton Ice Tea', calories: 30, protein: 0, fats: 0, carbs: 7 },
  { name: 'Квас', calories: 27, protein: 0.2, fats: 0, carbs: 5 },
  { name: 'Морс клюквенный', calories: 41, protein: 0.1, fats: 0, carbs: 10 },
  { name: 'Морс брусничный', calories: 40, protein: 0.1, fats: 0, carbs: 10 },
  { name: 'Компот из сухофруктов', calories: 60, protein: 0.4, fats: 0, carbs: 15 },
  { name: 'Red Bull', calories: 45, protein: 0.4, fats: 0, carbs: 11 },
  { name: 'Burn', calories: 48, protein: 0.2, fats: 0, carbs: 12 },
  { name: 'Adrenaline Rush', calories: 50, protein: 0.2, fats: 0, carbs: 12.5 },
  { name: 'Минералка без газа', calories: 0, protein: 0, fats: 0, carbs: 0 },
  { name: 'Минералка газированная', calories: 0, protein: 0, fats: 0, carbs: 0 },
  { name: 'Лимонад домашний', calories: 35, protein: 0, fats: 0, carbs: 8.5 },

  // ─── Кофе и чай (разные способы) ────────────────────────────────────────
  { name: 'Кофе чёрный', calories: 2, protein: 0.1, fats: 0, carbs: 0 },
  { name: 'Эспрессо', calories: 3, protein: 0.1, fats: 0, carbs: 0 },
  { name: 'Американо', calories: 5, protein: 0.1, fats: 0, carbs: 0 },
  { name: 'Капучино (200мл)', calories: 73, protein: 4, fats: 4, carbs: 6 },
  { name: 'Латте (250мл)', calories: 120, protein: 6, fats: 6, carbs: 10 },
  { name: 'Флэт Уайт (180мл)', calories: 90, protein: 5, fats: 5, carbs: 7 },
  { name: 'Раф-кофе', calories: 120, protein: 3, fats: 9, carbs: 7 },
  { name: 'Мокко', calories: 150, protein: 5, fats: 7, carbs: 16 },
  { name: 'Айс-латте', calories: 115, protein: 4.5, fats: 5, carbs: 12 },
  { name: 'Чай чёрный', calories: 2, protein: 0, fats: 0, carbs: 0.3 },
  { name: 'Чай с молоком', calories: 35, protein: 2, fats: 1.5, carbs: 3 },
  { name: 'Чай с лимоном', calories: 4, protein: 0, fats: 0, carbs: 1 },
  { name: 'Чай с сахаром (2 ложки)', calories: 38, protein: 0, fats: 0, carbs: 9.5 },
  { name: 'Матча латте', calories: 85, protein: 4, fats: 4, carbs: 7 },
  { name: 'Чай каркаде', calories: 5, protein: 0, fats: 0, carbs: 1 },

  // ─── Фрукты и ягоды (дополнительные) ────────────────────────────────────
  { name: 'Помело', calories: 38, protein: 0.8, fats: 0, carbs: 9.6 },
  { name: 'Папайя', calories: 43, protein: 0.5, fats: 0.3, carbs: 11 },
  { name: 'Кокос', calories: 354, protein: 3.3, fats: 33, carbs: 15 },
  { name: 'Инжир', calories: 74, protein: 0.8, fats: 0.3, carbs: 19 },
  { name: 'Изюм', calories: 299, protein: 3.1, fats: 0.5, carbs: 79 },
  { name: 'Облепиха', calories: 82, protein: 1.2, fats: 5.4, carbs: 5.7 },
  { name: 'Клюква', calories: 28, protein: 0.5, fats: 0.2, carbs: 6.8 },
  { name: 'Брусника', calories: 46, protein: 0.7, fats: 0.5, carbs: 8.2 },
  { name: 'Ежевика', calories: 43, protein: 2, fats: 1, carbs: 4.3 },
  { name: 'Крыжовник', calories: 45, protein: 0.7, fats: 0.2, carbs: 9.1 },
  { name: 'Смородина чёрная', calories: 44, protein: 1, fats: 0.4, carbs: 7.3 },
  { name: 'Смородина красная', calories: 43, protein: 0.6, fats: 0.2, carbs: 7.7 },

  // ─── Овощи и грибы (дополнительно) ──────────────────────────────────────
  { name: 'Лук зелёный', calories: 19, protein: 1.3, fats: 0, carbs: 3.2 },
  { name: 'Укроп', calories: 38, protein: 2.5, fats: 0.5, carbs: 6.3 },
  { name: 'Петрушка', calories: 47, protein: 3.7, fats: 0.4, carbs: 7.6 },
  { name: 'Кинза', calories: 23, protein: 2.1, fats: 0.5, carbs: 3.7 },
  { name: 'Базилик', calories: 27, protein: 3.2, fats: 0.6, carbs: 2.7 },
  { name: 'Салат айсберг', calories: 14, protein: 0.9, fats: 0.1, carbs: 3 },
  { name: 'Салат латук', calories: 12, protein: 1.2, fats: 0.3, carbs: 1.3 },
  { name: 'Руккола', calories: 25, protein: 2.6, fats: 0.7, carbs: 3.7 },
  { name: 'Шпинат свежий', calories: 23, protein: 2.9, fats: 0.4, carbs: 3.6 },
  { name: 'Грибы белые', calories: 34, protein: 3.7, fats: 1.7, carbs: 1.1 },
  { name: 'Грибы лисички', calories: 20, protein: 1.5, fats: 1.1, carbs: 1 },
  { name: 'Грибы опята', calories: 22, protein: 2.2, fats: 1.2, carbs: 0.5 },
  { name: 'Грибы вешенки', calories: 38, protein: 3.3, fats: 0.4, carbs: 6 },
  { name: 'Грибы белые сушёные', calories: 286, protein: 30, fats: 14, carbs: 9 },

  // ─── Специи и соусы ─────────────────────────────────────────────────────
  { name: 'Соль', calories: 0, protein: 0, fats: 0, carbs: 0 },
  { name: 'Сахар', calories: 399, protein: 0, fats: 0, carbs: 99.8 },
  { name: 'Сахар коричневый', calories: 380, protein: 0, fats: 0, carbs: 98 },
  { name: 'Сахарозаменитель', calories: 0, protein: 0, fats: 0, carbs: 0 },
  { name: 'Сироп кленовый', calories: 260, protein: 0, fats: 0.1, carbs: 67 },
  { name: 'Соус тартар', calories: 330, protein: 0.8, fats: 35, carbs: 3.5 },
  { name: 'Соус сырный', calories: 230, protein: 4, fats: 20, carbs: 8 },
  { name: 'Горчица', calories: 143, protein: 9.9, fats: 6.7, carbs: 5.3 },
  { name: 'Хрен', calories: 59, protein: 3.2, fats: 0.4, carbs: 10.5 },
  { name: 'Уксус яблочный', calories: 22, protein: 0, fats: 0, carbs: 0.9 },
  { name: 'Уксус бальзамический', calories: 88, protein: 0.5, fats: 0, carbs: 17 },
  { name: 'Терияки соус', calories: 89, protein: 5.9, fats: 0, carbs: 15 },
  { name: 'Соус чили-сладкий', calories: 165, protein: 0.5, fats: 0.5, carbs: 40 },
  { name: 'Соус песто', calories: 464, protein: 5, fats: 45, carbs: 6 },
  { name: 'Соус айоли', calories: 490, protein: 1.5, fats: 51, carbs: 2 },
  { name: 'Соус бешамель', calories: 131, protein: 3.5, fats: 7.5, carbs: 13 },

  // ─── Растительные масла и жиры ──────────────────────────────────────────
  { name: 'Масло кокосовое', calories: 892, protein: 0, fats: 99.1, carbs: 0 },
  { name: 'Масло льняное', calories: 898, protein: 0, fats: 100, carbs: 0 },
  { name: 'Масло кунжутное', calories: 884, protein: 0, fats: 100, carbs: 0 },
  { name: 'Масло топлёное', calories: 892, protein: 0.3, fats: 99, carbs: 0 },
  { name: 'Масло рапсовое', calories: 884, protein: 0, fats: 100, carbs: 0 },
  { name: 'Маргарин', calories: 720, protein: 0.5, fats: 80, carbs: 1 },
  { name: 'Сало', calories: 797, protein: 2.4, fats: 89, carbs: 0 },

  // ─── Диетические / фитнес продукты ──────────────────────────────────────
  { name: 'Протеиновый шейк молочный', calories: 80, protein: 18, fats: 0.5, carbs: 2 },
  { name: 'BCAA порошок', calories: 40, protein: 10, fats: 0, carbs: 0 },
  { name: 'Креатин моногидрат', calories: 0, protein: 0, fats: 0, carbs: 0 },
  { name: 'Энергетический гель (1 шт)', calories: 90, protein: 0, fats: 0, carbs: 22 },
  { name: 'Протеиновое мороженое', calories: 90, protein: 13, fats: 1, carbs: 8 },
  { name: 'Протеиновый пудинг', calories: 95, protein: 15, fats: 1, carbs: 6 },
  { name: 'Протеиновые чипсы', calories: 380, protein: 40, fats: 15, carbs: 25 },
  { name: 'Протеиновые блины (сухая смесь)', calories: 340, protein: 55, fats: 4, carbs: 18 },
  { name: 'Низкокалорийный сироп', calories: 7, protein: 0, fats: 0, carbs: 1.5 },
  { name: 'Арахисовая паста без сахара', calories: 580, protein: 27, fats: 50, carbs: 13 },
  { name: 'Протеиновая каша', calories: 340, protein: 25, fats: 8, carbs: 40 },

  // ─── Завтраки популярные / хлопья ──────────────────────────────────────
  { name: 'Хлопья Nesquik', calories: 390, protein: 6, fats: 3.5, carbs: 80 },
  { name: 'Хлопья Cheerios', calories: 370, protein: 11, fats: 6, carbs: 73 },
  { name: 'Хлопья Корнфлекс', calories: 357, protein: 7.5, fats: 0.9, carbs: 82 },
  { name: 'Мюсли с орехами', calories: 387, protein: 10, fats: 11, carbs: 62 },
  { name: 'Гранола', calories: 450, protein: 10, fats: 20, carbs: 60 },
  { name: 'Овсяная каша быстрая (пакет)', calories: 370, protein: 9, fats: 6, carbs: 68 },
  { name: 'Яичница-глазунья (2 яйца)', calories: 200, protein: 13, fats: 16, carbs: 1 },
  { name: 'Омлет с сыром', calories: 210, protein: 14, fats: 17, carbs: 1.5 },
  { name: 'Омлет с овощами', calories: 130, protein: 9, fats: 9, carbs: 3 },
  { name: 'Омлет с ветчиной', calories: 175, protein: 14, fats: 12, carbs: 2 },
  { name: 'Тост с авокадо', calories: 240, protein: 6, fats: 14, carbs: 24 },
  { name: 'Тост с яйцом', calories: 200, protein: 10, fats: 9, carbs: 20 },
  { name: 'Тост с сыром', calories: 280, protein: 11, fats: 15, carbs: 24 },
  { name: 'Смузи-боул', calories: 180, protein: 5, fats: 4, carbs: 30 },

  // ─── Снэки и перекусы ──────────────────────────────────────────────────
  { name: 'Попкорн без масла', calories: 387, protein: 13, fats: 4.5, carbs: 78 },
  { name: 'Попкорн карамельный', calories: 485, protein: 3, fats: 13, carbs: 90 },
  { name: 'Попкорн сырный', calories: 465, protein: 9, fats: 25, carbs: 55 },
  { name: 'Снэк-микс орехи+сухофрукты', calories: 420, protein: 10, fats: 22, carbs: 45 },
  { name: 'Сухарики со вкусом', calories: 400, protein: 9, fats: 15, carbs: 58 },
  { name: 'Кукурузные палочки', calories: 518, protein: 8, fats: 29, carbs: 55 },
  { name: 'Вафли венские', calories: 420, protein: 7, fats: 20, carbs: 55 },
  { name: 'Вафли ванильные', calories: 340, protein: 4, fats: 12, carbs: 56 },
  { name: 'Бисквитный корж', calories: 310, protein: 6, fats: 6, carbs: 58 },
  { name: 'Пряник', calories: 335, protein: 4.8, fats: 2.8, carbs: 75 },
  { name: 'Тульский пряник с начинкой', calories: 360, protein: 5, fats: 7, carbs: 70 },

  // ─── Веганские и растительные альтернативы ─────────────────────────────
  { name: 'Темпе', calories: 193, protein: 19, fats: 11, carbs: 9 },
  { name: 'Сейтан', calories: 370, protein: 75, fats: 2, carbs: 14 },
  { name: 'Веганский бургер (котлета)', calories: 220, protein: 18, fats: 14, carbs: 8 },
  { name: 'Веганские сосиски', calories: 195, protein: 18, fats: 12, carbs: 6 },
  { name: 'Растительное молоко соевое', calories: 54, protein: 3.3, fats: 1.8, carbs: 6 },
  { name: 'Тофу копчёный', calories: 100, protein: 12, fats: 5, carbs: 2 },
  { name: 'Нутовая мука', calories: 387, protein: 22, fats: 6, carbs: 58 },

  // ─── Замороженные и готовые полуфабрикаты ──────────────────────────────
  { name: 'Пельмени домашние с говядиной', calories: 275, protein: 13, fats: 14, carbs: 23 },
  { name: 'Пельмени с курицей', calories: 250, protein: 14, fats: 10, carbs: 25 },
  { name: 'Вареники с вишней', calories: 170, protein: 4.5, fats: 1, carbs: 36 },
  { name: 'Вареники с творогом', calories: 170, protein: 8, fats: 4, carbs: 26 },
  { name: 'Наггетсы замороженные', calories: 255, protein: 14, fats: 15, carbs: 17 },
  { name: 'Котлеты полуфабрикат', calories: 240, protein: 13, fats: 16, carbs: 10 },
  { name: 'Блинчики с мясом', calories: 192, protein: 9, fats: 9, carbs: 19 },
  { name: 'Блинчики с творогом', calories: 185, protein: 8, fats: 8, carbs: 20 },
  { name: 'Блинчики с вишней', calories: 170, protein: 4, fats: 5, carbs: 27 },
  { name: 'Чебуреки замороженные', calories: 264, protein: 9, fats: 15, carbs: 23 },
  { name: 'Хинкали замороженные', calories: 235, protein: 12, fats: 11, carbs: 22 },
  { name: 'Манты замороженные', calories: 215, protein: 10, fats: 10, carbs: 22 },
];

/** Normalize a food name for dedup: lowercase, collapse whitespace, strip
 *  common decorative punctuation so "Шоколад тёмный 70%" and "Шоколад горький (70%)"
 *  can be detected as the same product. Unicode-safe. */
const normalizeFoodKey = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[()%]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

// Collapse duplicates by normalized name. If two entries with the same
// normalized name have noticeably different macros (e.g. "Гречка варёная" vs
// "Гречка сухая"), we keep both — the raw-vs-cooked distinction matters.
const seenByKey = new Map<string, typeof RAW_FOOD_DB[number]>();
for (const item of RAW_FOOD_DB) {
  const key = normalizeFoodKey(item.name);
  const existing = seenByKey.get(key);
  if (!existing) {
    seenByKey.set(key, item);
    continue;
  }
  // Same normalized name — merge only if macros are within ~5% (same product
  // written two ways). Otherwise keep the first (raw/cooked/variant distinction).
  const close = (a: number, b: number) => Math.abs(a - b) <= Math.max(1, Math.abs(a) * 0.05);
  if (
    close(existing.calories, item.calories) &&
    close(existing.protein, item.protein) &&
    close(existing.fats, item.fats) &&
    close(existing.carbs, item.carbs)
  ) {
    // drop duplicate silently
    continue;
  }
  // Macros diverge — keep both under distinct keys so the user can still find them
  seenByKey.set(`${key}__${item.calories}`, item);
}

export const FOOD_DB = Array.from(seenByKey.values());

export type FoodItem = typeof FOOD_DB[0];
