// Common foods database (per 100g)
export const FOOD_DB = [
  // Мясо и птица
  { name: 'Куриная грудка', calories: 165, protein: 31, fats: 3.6, carbs: 0 },
  { name: 'Куриное бедро', calories: 215, protein: 26, fats: 12, carbs: 0 },
  { name: 'Индейка (грудка)', calories: 157, protein: 29, fats: 3.2, carbs: 0 },
  { name: 'Говядина (фарш)', calories: 250, protein: 26, fats: 17, carbs: 0 },
  { name: 'Говядина (вырезка)', calories: 187, protein: 29, fats: 7, carbs: 0 },
  { name: 'Свинина (корейка)', calories: 270, protein: 23, fats: 19, carbs: 0 },
  { name: 'Свинина (вырезка)', calories: 143, protein: 22, fats: 6, carbs: 0 },
  { name: 'Докторская колбаса', calories: 256, protein: 13, fats: 22, carbs: 2 },
  { name: 'Куриная варёная колбаса', calories: 170, protein: 16, fats: 10, carbs: 5 },
  // Рыба и морепродукты
  { name: 'Лосось', calories: 208, protein: 20, fats: 13, carbs: 0 },
  { name: 'Горбуша', calories: 142, protein: 21, fats: 7, carbs: 0 },
  { name: 'Скумбрия', calories: 191, protein: 18, fats: 13, carbs: 0 },
  { name: 'Треска', calories: 75, protein: 17, fats: 0.6, carbs: 0 },
  { name: 'Минтай', calories: 72, protein: 16, fats: 0.9, carbs: 0 },
  { name: 'Тунец консервированный', calories: 116, protein: 25, fats: 1, carbs: 0 },
  { name: 'Сельдь солёная', calories: 217, protein: 17, fats: 16, carbs: 0 },
  // Яйца и молочное
  { name: 'Яйцо куриное', calories: 155, protein: 13, fats: 11, carbs: 1.1 },
  { name: 'Яичный белок', calories: 52, protein: 11, fats: 0.2, carbs: 0.7 },
  { name: 'Творог 0%', calories: 71, protein: 16, fats: 0, carbs: 1.8 },
  { name: 'Творог 5%', calories: 121, protein: 17, fats: 5, carbs: 1.8 },
  { name: 'Творог 9%', calories: 159, protein: 16, fats: 9, carbs: 2 },
  { name: 'Греческий йогурт', calories: 59, protein: 10, fats: 0.4, carbs: 3.6 },
  { name: 'Йогурт 2.5%', calories: 53, protein: 4.3, fats: 2.5, carbs: 3.5 },
  { name: 'Кефир 1%', calories: 40, protein: 3.3, fats: 1, carbs: 4.7 },
  { name: 'Ряженка 2.5%', calories: 54, protein: 2.9, fats: 2.5, carbs: 4.2 },
  { name: 'Молоко 3.2%', calories: 60, protein: 3.2, fats: 3.2, carbs: 4.7 },
  { name: 'Сметана 15%', calories: 158, protein: 2.6, fats: 15, carbs: 3 },
  { name: 'Сыр твёрдый', calories: 356, protein: 26, fats: 27, carbs: 0.4 },
  { name: 'Сыр плавленый', calories: 261, protein: 16, fats: 20, carbs: 3 },
  { name: 'Протеин (сывороточный)', calories: 380, protein: 74, fats: 5, carbs: 10 },
  // Крупы и злаки
  { name: 'Гречка (варёная)', calories: 110, protein: 4.2, fats: 0.6, carbs: 21 },
  { name: 'Гречка (сухая)', calories: 313, protein: 12, fats: 3.3, carbs: 57 },
  { name: 'Рис (варёный)', calories: 130, protein: 2.7, fats: 0.3, carbs: 28 },
  { name: 'Овсянка (варёная)', calories: 68, protein: 2.4, fats: 1.4, carbs: 12 },
  { name: 'Овсяные хлопья (сухие)', calories: 352, protein: 12, fats: 6, carbs: 60 },
  { name: 'Перловка варёная', calories: 109, protein: 3.1, fats: 0.4, carbs: 22 },
  { name: 'Пшено варёное', calories: 90, protein: 3, fats: 0.7, carbs: 18 },
  { name: 'Макароны (варёные)', calories: 158, protein: 5.5, fats: 0.9, carbs: 31 },
  // Хлеб
  { name: 'Хлеб цельнозерновой', calories: 247, protein: 8, fats: 2, carbs: 48 },
  { name: 'Хлеб чёрный (Бородинский)', calories: 201, protein: 6.8, fats: 1.3, carbs: 40 },
  { name: 'Батон белый', calories: 264, protein: 7.9, fats: 3.4, carbs: 50 },
  { name: 'Хлебцы рисовые', calories: 363, protein: 8, fats: 2.8, carbs: 76 },
  // Бобовые
  { name: 'Нут (варёный)', calories: 164, protein: 9, fats: 2.6, carbs: 27 },
  { name: 'Чечевица (варёная)', calories: 116, protein: 9, fats: 0.4, carbs: 20 },
  { name: 'Фасоль (варёная)', calories: 127, protein: 8.7, fats: 0.5, carbs: 22 },
  // Овощи
  { name: 'Картофель (варёный)', calories: 87, protein: 1.9, fats: 0.1, carbs: 20 },
  { name: 'Брокколи', calories: 34, protein: 2.8, fats: 0.4, carbs: 6.6 },
  { name: 'Капуста белокочанная', calories: 27, protein: 1.8, fats: 0.1, carbs: 4.7 },
  { name: 'Огурец', calories: 15, protein: 0.8, fats: 0.1, carbs: 2.5 },
  { name: 'Помидор', calories: 20, protein: 0.9, fats: 0.2, carbs: 3.9 },
  { name: 'Морковь', calories: 41, protein: 0.9, fats: 0.2, carbs: 9.6 },
  { name: 'Свекла (варёная)', calories: 49, protein: 1.8, fats: 0.1, carbs: 10 },
  { name: 'Шпинат', calories: 23, protein: 2.9, fats: 0.4, carbs: 3.6 },
  // Фрукты
  { name: 'Банан', calories: 89, protein: 1.1, fats: 0.3, carbs: 23 },
  { name: 'Яблоко', calories: 52, protein: 0.3, fats: 0.2, carbs: 14 },
  { name: 'Апельсин', calories: 47, protein: 0.9, fats: 0.1, carbs: 12 },
  { name: 'Клубника', calories: 32, protein: 0.7, fats: 0.3, carbs: 7.7 },
  { name: 'Вишня', calories: 52, protein: 0.8, fats: 0.5, carbs: 12 },
  // Орехи и масла
  { name: 'Орехи грецкие', calories: 654, protein: 15, fats: 65, carbs: 14 },
  { name: 'Миндаль', calories: 579, protein: 21, fats: 50, carbs: 22 },
  { name: 'Арахисовая паста', calories: 588, protein: 25, fats: 50, carbs: 20 },
  { name: 'Семечки подсолнечника', calories: 584, protein: 21, fats: 53, carbs: 11 },
  { name: 'Авокадо', calories: 160, protein: 2, fats: 15, carbs: 9 },
  { name: 'Оливковое масло', calories: 884, protein: 0, fats: 100, carbs: 0 },
  { name: 'Подсолнечное масло', calories: 884, protein: 0, fats: 100, carbs: 0 },
  // Прочее
  { name: 'Мёд', calories: 304, protein: 0.8, fats: 0, carbs: 82 },
  { name: 'Шоколад тёмный 70%', calories: 598, protein: 7.8, fats: 43, carbs: 46 },
  { name: 'Шоколад молочный', calories: 550, protein: 6.9, fats: 35, carbs: 52 },
  // Спортивное питание
  { name: 'Протеин казеиновый', calories: 370, protein: 76, fats: 4, carbs: 6 },
  { name: 'Гейнер', calories: 380, protein: 20, fats: 3, carbs: 70 },
  { name: 'Протеиновый батончик', calories: 370, protein: 30, fats: 12, carbs: 35 },
  { name: 'Изолят сывороточного белка', calories: 360, protein: 85, fats: 1, carbs: 5 },
  { name: 'Яичный протеин', calories: 365, protein: 78, fats: 2, carbs: 7 },
  // Готовые блюда
  { name: 'Куриная грудка варёная', calories: 137, protein: 27, fats: 3, carbs: 0 },
  { name: 'Куриная грудка запечённая', calories: 167, protein: 28, fats: 5, carbs: 1 },
  { name: 'Куриная грудка тушёная', calories: 144, protein: 26, fats: 4, carbs: 1 },
  { name: 'Котлета домашняя', calories: 230, protein: 15, fats: 16, carbs: 8 },
  { name: 'Пельмени варёные', calories: 245, protein: 11, fats: 10, carbs: 29 },
  { name: 'Борщ со сметаной', calories: 55, protein: 2.5, fats: 3, carbs: 5 },
  { name: 'Гречка с куриной грудкой', calories: 130, protein: 14, fats: 2, carbs: 15 },
  { name: 'Рис с курицей', calories: 140, protein: 13, fats: 2.5, carbs: 17 },
  { name: 'Овсянка с бананом', calories: 110, protein: 3.5, fats: 2, carbs: 21 },
  // Молочные продукты и снеки
  { name: 'Сырок творожный глазированный', calories: 330, protein: 8, fats: 20, carbs: 29 },
  { name: 'Мороженое пломбир', calories: 230, protein: 3.5, fats: 12, carbs: 27 },
  { name: 'Кефир 2.5%', calories: 53, protein: 3.2, fats: 2.5, carbs: 4.1 },
  { name: 'Хлебцы гречневые', calories: 330, protein: 12, fats: 3, carbs: 64 },
  { name: 'Зефир', calories: 304, protein: 0.8, fats: 0, carbs: 77 },
  { name: 'Финики', calories: 277, protein: 1.8, fats: 0.2, carbs: 75 },
  { name: 'Курага', calories: 241, protein: 3.4, fats: 0.4, carbs: 60 },
  { name: 'Чернослив', calories: 240, protein: 2.3, fats: 0.7, carbs: 57 },
  // Напитки
  { name: 'Молоко 1.5%', calories: 46, protein: 3, fats: 1.5, carbs: 4.7 },
  { name: 'Апельсиновый сок', calories: 45, protein: 0.7, fats: 0.2, carbs: 10 },
  { name: 'Томатный сок', calories: 21, protein: 1, fats: 0.1, carbs: 4.2 },
  // Дополнительные продукты
  { name: 'Тыква варёная', calories: 22, protein: 1, fats: 0.1, carbs: 4.4 },
  { name: 'Кабачок варёный', calories: 24, protein: 0.7, fats: 0.3, carbs: 4.6 },
  { name: 'Перец болгарский', calories: 27, protein: 0.9, fats: 0.3, carbs: 6 },
  { name: 'Цветная капуста варёная', calories: 29, protein: 2.3, fats: 0.3, carbs: 5 },
  { name: 'Кальмар варёный', calories: 110, protein: 22, fats: 1.2, carbs: 2 },
  { name: 'Семга слабосолёная', calories: 202, protein: 21, fats: 13, carbs: 0 },
  { name: 'Сардины в масле (консервы)', calories: 208, protein: 20, fats: 14, carbs: 0 },
  { name: 'Рис бурый варёный', calories: 111, protein: 2.6, fats: 0.9, carbs: 23 },
  { name: 'Картофельное пюре', calories: 90, protein: 2, fats: 3, carbs: 14 },
  { name: 'Омлет (2 яйца)', calories: 154, protein: 11, fats: 12, carbs: 1.5 },
  { name: 'Суп куриный с лапшой', calories: 40, protein: 3, fats: 1.5, carbs: 4 },
  { name: 'Запеканка творожная', calories: 185, protein: 14, fats: 8, carbs: 15 },
  { name: 'Кукурузная каша', calories: 86, protein: 2.5, fats: 0.5, carbs: 18 },
  { name: 'Тофу', calories: 76, protein: 8, fats: 4.8, carbs: 1.9 },
  { name: 'Чечевичный суп', calories: 63, protein: 4, fats: 1.5, carbs: 9 },
  { name: 'Оливки', calories: 145, protein: 1, fats: 15, carbs: 3.8 },
  { name: 'Майонез', calories: 680, protein: 2.8, fats: 74, carbs: 2.6 },
  { name: 'Кетчуп', calories: 93, protein: 1.8, fats: 0.1, carbs: 22 },
  { name: 'Сметана 20%', calories: 206, protein: 2.8, fats: 20, carbs: 3.2 },
  { name: 'Сыр Моцарелла', calories: 280, protein: 22, fats: 21, carbs: 2.2 },
  { name: 'Сыр Рикотта', calories: 174, protein: 11, fats: 13, carbs: 3 },
  { name: 'Грибы шампиньоны', calories: 27, protein: 4.3, fats: 1, carbs: 1 },
  { name: 'Чеснок', calories: 149, protein: 6.4, fats: 0.5, carbs: 33 },
  { name: 'Лук репчатый', calories: 41, protein: 1.1, fats: 0.1, carbs: 8.5 },
  // Фрукты и ягоды (дополнительные)
  { name: 'Виноград', calories: 67, protein: 0.6, fats: 0.2, carbs: 17 },
  { name: 'Арбуз', calories: 27, protein: 0.7, fats: 0.1, carbs: 6.8 },
  { name: 'Дыня', calories: 33, protein: 0.8, fats: 0.1, carbs: 7.7 },
  { name: 'Мандарин', calories: 40, protein: 0.8, fats: 0.2, carbs: 9.2 },
  { name: 'Груша', calories: 42, protein: 0.4, fats: 0.3, carbs: 11 },
  { name: 'Персик', calories: 39, protein: 0.9, fats: 0.1, carbs: 9.5 },
  { name: 'Черника', calories: 44, protein: 0.7, fats: 0.5, carbs: 10 },
  { name: 'Малина', calories: 46, protein: 1.2, fats: 0.8, carbs: 9 },
  { name: 'Голубика', calories: 57, protein: 0.7, fats: 0.3, carbs: 14 },
  { name: 'Гранат', calories: 83, protein: 1.7, fats: 1.2, carbs: 19 },
  { name: 'Манго', calories: 60, protein: 0.8, fats: 0.4, carbs: 15 },
  { name: 'Ананас', calories: 50, protein: 0.5, fats: 0.1, carbs: 13 },
  { name: 'Киви', calories: 61, protein: 1.1, fats: 0.5, carbs: 14 },
  // Овощи (дополнительные)
  { name: 'Батат (варёный)', calories: 86, protein: 2, fats: 0.1, carbs: 20 },
  { name: 'Спаржа', calories: 20, protein: 2.2, fats: 0.1, carbs: 3.9 },
  { name: 'Сельдерей', calories: 16, protein: 0.7, fats: 0.1, carbs: 3.6 },
  { name: 'Редис', calories: 20, protein: 1.2, fats: 0.1, carbs: 3.4 },
  { name: 'Кукуруза варёная', calories: 123, protein: 4, fats: 2.4, carbs: 22 },
  { name: 'Горошек зелёный', calories: 82, protein: 5.4, fats: 0.4, carbs: 14 },
  { name: 'Баклажан', calories: 24, protein: 1.2, fats: 0.1, carbs: 5.5 },
  // Зерновые и хлеб (дополнительные)
  { name: 'Лаваш армянский', calories: 277, protein: 9, fats: 1.1, carbs: 58 },
  { name: 'Киноа варёная', calories: 120, protein: 4.4, fats: 1.9, carbs: 21 },
  { name: 'Булгур варёный', calories: 83, protein: 3, fats: 0.2, carbs: 18 },
  { name: 'Овсяноблин', calories: 140, protein: 10, fats: 5, carbs: 14 },
  // Молочные (дополнительные)
  { name: 'Творожный сыр (рикотта/крем-чиз)', calories: 260, protein: 7, fats: 24, carbs: 3.2 },
  { name: 'Пармезан', calories: 392, protein: 36, fats: 26, carbs: 0 },
  { name: 'Брынза', calories: 260, protein: 17, fats: 20, carbs: 0.5 },
  { name: 'Молоко 2.5%', calories: 54, protein: 2.9, fats: 2.5, carbs: 4.7 },
  // Напитки (дополнительные)
  { name: 'Кофе с молоком', calories: 38, protein: 1.8, fats: 1.9, carbs: 3.7 },
  { name: 'Зелёный чай', calories: 2, protein: 0, fats: 0, carbs: 0 },
  // Рыба (дополнительные)
  { name: 'Тунец в собственном соку', calories: 99, protein: 23, fats: 0.5, carbs: 0 },
  { name: 'Креветки варёные', calories: 99, protein: 21, fats: 1.1, carbs: 0 },
  { name: 'Карп запечённый', calories: 121, protein: 18, fats: 5, carbs: 0 },
  // Готовые блюда и фастфуд
  { name: 'Сырники (2 шт)', calories: 220, protein: 14, fats: 9, carbs: 22 },
  { name: 'Блины (2 шт)', calories: 180, protein: 6, fats: 7, carbs: 24 },
  { name: 'Вареники с картошкой', calories: 195, protein: 6, fats: 4, carbs: 34 },
  { name: 'Салат Цезарь', calories: 180, protein: 9, fats: 13, carbs: 8 },
  { name: 'Оливье', calories: 198, protein: 6, fats: 15, carbs: 12 },
  { name: 'Пицца (1 кусок, 100г)', calories: 270, protein: 12, fats: 12, carbs: 30 },
  { name: 'Шашлык из свинины', calories: 218, protein: 19, fats: 15, carbs: 2 },
  { name: 'Шашлык из курицы', calories: 158, protein: 24, fats: 7, carbs: 0 },
  { name: 'Котлета рыбная', calories: 165, protein: 16, fats: 9, carbs: 6 },
  { name: 'Роллы (Калифорния, 100г)', calories: 146, protein: 7, fats: 4.5, carbs: 20 },
  // Колбасные изделия
  { name: 'Сосиски молочные', calories: 266, protein: 12, fats: 24, carbs: 1.8 },
  { name: 'Сардельки', calories: 332, protein: 11, fats: 31, carbs: 1.4 },
  // Молочные (дополнительные)
  { name: 'Сыр Гауда', calories: 356, protein: 25, fats: 28, carbs: 2.2 },
  { name: 'Сыр Чеддер', calories: 402, protein: 23, fats: 34, carbs: 1.3 },
  { name: 'Сыр Фета', calories: 264, protein: 14, fats: 21, carbs: 4.1 },
  // Напитки
  { name: 'Молочный коктейль', calories: 85, protein: 3.4, fats: 2.5, carbs: 12 },
  { name: 'Сок апельсиновый', calories: 45, protein: 0.7, fats: 0.2, carbs: 10 },
  { name: 'Сок яблочный', calories: 46, protein: 0.5, fats: 0.1, carbs: 11 },
  { name: 'Компот (без сахара)', calories: 30, protein: 0.2, fats: 0.1, carbs: 7 },
  // Яйца (способы приготовления)
  { name: 'Яйцо варёное вкрутую', calories: 155, protein: 13, fats: 11, carbs: 1.1 },
  { name: 'Яйцо варёное всмятку', calories: 143, protein: 13, fats: 10, carbs: 0.7 },
  // Сладкое
  { name: 'Печенье овсяное', calories: 437, protein: 6, fats: 18, carbs: 63 },
  // Супы (средняя порция 250г)
  { name: 'Борщ (250г)', calories: 68, protein: 3, fats: 3, carbs: 7 },
  { name: 'Щи (250г)', calories: 48, protein: 2.5, fats: 2.2, carbs: 5 },
  { name: 'Куриный суп (250г)', calories: 52, protein: 5, fats: 2, carbs: 4 },
  { name: 'Гречневый суп (250г)', calories: 60, protein: 3.5, fats: 2, carbs: 7 },
  { name: 'Рассольник (250г)', calories: 55, protein: 3, fats: 2.5, carbs: 6 },
  { name: 'Уха (250г)', calories: 45, protein: 6, fats: 1.5, carbs: 3 },
  // Каши (приготовленные)
  { name: 'Манная каша на молоке', calories: 100, protein: 3.3, fats: 2.5, carbs: 16 },
  { name: 'Ячневая каша', calories: 88, protein: 2.5, fats: 0.4, carbs: 19 },
  // Мясные блюда
  { name: 'Пельмени (варёные)', calories: 247, protein: 11, fats: 10, carbs: 29 },
  { name: 'Манты (1 шт)', calories: 180, protein: 9, fats: 8, carbs: 19 },
  { name: 'Бефстроганов', calories: 175, protein: 16, fats: 11, carbs: 4 },
  { name: 'Голубцы в соусе', calories: 135, protein: 10, fats: 7, carbs: 10 },
  { name: 'Котлета говяжья', calories: 220, protein: 17, fats: 14, carbs: 7 },
  { name: 'Ростбиф', calories: 190, protein: 28, fats: 9, carbs: 0 },
  { name: 'Гамбургер (булочка+котлета)', calories: 295, protein: 17, fats: 14, carbs: 24 },
  // Салаты (100г)
  { name: 'Греческий салат', calories: 74, protein: 2.4, fats: 5.5, carbs: 5 },
  { name: 'Капустный салат', calories: 40, protein: 1.5, fats: 2, carbs: 5 },
  { name: 'Морковь по-корейски', calories: 112, protein: 1.3, fats: 7, carbs: 11 },
  { name: 'Свёкла варёная с чесноком', calories: 65, protein: 1.8, fats: 2.5, carbs: 9 },
  // Орехи и семечки
  { name: 'Арахис', calories: 567, protein: 26, fats: 49, carbs: 16 },
  { name: 'Кунжут', calories: 573, protein: 18, fats: 50, carbs: 23 },
  { name: 'Тыквенные семечки', calories: 559, protein: 30, fats: 49, carbs: 11 },
  { name: 'Подсолнечные семечки', calories: 601, protein: 21, fats: 53, carbs: 20 },
  { name: 'Фундук', calories: 628, protein: 15, fats: 61, carbs: 17 },
  // Бобовые
  { name: 'Чечевица варёная', calories: 116, protein: 9, fats: 0.4, carbs: 20 },
  { name: 'Нут варёный', calories: 164, protein: 9, fats: 2.6, carbs: 27 },
  { name: 'Эдамаме (соевые бобы)', calories: 121, protein: 11, fats: 5, carbs: 9 },
  // Дополнительные фрукты
  { name: 'Грейпфрут', calories: 42, protein: 0.8, fats: 0.1, carbs: 10 },
  { name: 'Слива', calories: 46, protein: 0.7, fats: 0.3, carbs: 11 },
  { name: 'Хурма', calories: 67, protein: 0.5, fats: 0.4, carbs: 16 },
  // Хлебцы и снэки
  { name: 'Крекеры цельнозерновые', calories: 400, protein: 10, fats: 10, carbs: 70 },
  { name: 'Чипсы картофельные', calories: 536, protein: 7, fats: 30, carbs: 62 },
  // Соусы и заправки
  { name: 'Арахисовое масло', calories: 588, protein: 25, fats: 50, carbs: 20 },
  { name: 'Томатная паста', calories: 82, protein: 4.8, fats: 0.5, carbs: 17 },
  // Хлебобулочные
  { name: 'Батон нарезной', calories: 262, protein: 8, fats: 3.3, carbs: 49 },
  { name: 'Хлеб бородинский', calories: 207, protein: 6.8, fats: 1.3, carbs: 41 },
  { name: 'Рогалик', calories: 315, protein: 9, fats: 9, carbs: 51 },
  // Прочие популярные продукты
  { name: 'Лапша быстрого приготовления', calories: 363, protein: 8, fats: 14, carbs: 52 },
  { name: 'Пельмени замороженные', calories: 197, protein: 9, fats: 7, carbs: 25 },
  { name: 'Шоколад горький (70%)', calories: 547, protein: 8, fats: 35, carbs: 52 },
  { name: 'Варенье', calories: 268, protein: 0.3, fats: 0.1, carbs: 70 },
  // Рыба и морепродукты (дополнительные)
  { name: 'Форель', calories: 148, protein: 20, fats: 7, carbs: 0 },
  { name: 'Сёмга запечённая', calories: 196, protein: 24, fats: 11, carbs: 0 },
  { name: 'Шпроты в масле', calories: 363, protein: 18, fats: 32, carbs: 0 },
  { name: 'Икра красная', calories: 251, protein: 32, fats: 14, carbs: 0 },
  { name: 'Морская капуста', calories: 5, protein: 0.6, fats: 0.1, carbs: 0.7 },
  { name: 'Мидии варёные', calories: 86, protein: 12, fats: 2, carbs: 3.7 },
  // Мясо и птица (дополнительные)
  { name: 'Курица жареная', calories: 238, protein: 25, fats: 15, carbs: 0 },
  { name: 'Утка запечённая', calories: 308, protein: 22, fats: 24, carbs: 0 },
  { name: 'Кролик тушёный', calories: 179, protein: 21, fats: 9, carbs: 3 },
  { name: 'Печень куриная', calories: 138, protein: 19, fats: 5, carbs: 3 },
  { name: 'Печень говяжья', calories: 127, protein: 20, fats: 3.7, carbs: 4.2 },
  // Овощи (дополнительные)
  { name: 'Цветная капуста', calories: 30, protein: 2.5, fats: 0.3, carbs: 5 },
  { name: 'Кабачок', calories: 24, protein: 0.7, fats: 0.3, carbs: 5 },
  { name: 'Тыква', calories: 26, protein: 1, fats: 0.1, carbs: 6 },
  { name: 'Болгарский перец красный', calories: 31, protein: 1, fats: 0.3, carbs: 6 },
  { name: 'Артишок', calories: 47, protein: 3.3, fats: 0.2, carbs: 11 },
  // Молочное (дополнительные)
  { name: 'Творожная масса с изюмом', calories: 257, protein: 8, fats: 9, carbs: 38 },
  { name: 'Ряженка 4%', calories: 67, protein: 2.8, fats: 4, carbs: 4.9 },
  { name: 'Масло сливочное', calories: 748, protein: 0.8, fats: 82, carbs: 0.8 },
  { name: 'Сыр Брынза', calories: 262, protein: 17, fats: 20, carbs: 0.4 },
  // Фрукты и ягоды (дополнительные)
  { name: 'Нектарин', calories: 44, protein: 1, fats: 0.3, carbs: 10 },
  { name: 'Абрикос', calories: 44, protein: 0.9, fats: 0.3, carbs: 10 },
  // Напитки (дополнительные)
  { name: 'Кофе с молоком (150мл)', calories: 40, protein: 1.5, fats: 1.5, carbs: 4 },
  { name: 'Какао на молоке', calories: 92, protein: 4.5, fats: 3.5, carbs: 11 },
  { name: 'Кефир 3.2%', calories: 59, protein: 2.9, fats: 3.2, carbs: 3.8 },
  // Снэки и фастфуд
  { name: 'Горсть орехов (30г)', calories: 183, protein: 5, fats: 17, carbs: 6 },
  { name: 'Шаурма куриная', calories: 210, protein: 14, fats: 10, carbs: 18 },
  { name: 'Блин (1 шт, 50г)', calories: 108, protein: 3, fats: 4, carbs: 15 },
  { name: 'Сырник творожный', calories: 220, protein: 12, fats: 10, carbs: 22 },
  { name: 'Оладьи', calories: 205, protein: 7, fats: 9, carbs: 26 },
];

export type FoodItem = typeof FOOD_DB[0];
